/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as RelatorioFinanceiroRouteImport } from './routes/relatorio-financeiro'
import { Route as ReferenciasRouteImport } from './routes/referencias'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappIndexRouteImport } from './routes/whatsapp.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PeticionamentoIndexRouteImport } from './routes/peticionamento.index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards.index'
import { Route as ControladoriaIndexRouteImport } from './routes/controladoria.index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as ComercialIndexRouteImport } from './routes/comercial.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as CasosIndexRouteImport } from './routes/casos.index'
import { Route as WhatsappAgenteRouteImport } from './routes/whatsapp.agente'
import { Route as PortalPerfilRouteImport } from './routes/portal.perfil'
import { Route as PortalMensagensRouteImport } from './routes/portal.mensagens'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as PortalBoletosRouteImport } from './routes/portal.boletos'
import { Route as PeticionamentoBancoPecasRouteImport } from './routes/peticionamento.banco-pecas'
import { Route as PeticionamentoIdRouteImport } from './routes/peticionamento.$id'
import { Route as PainelResultadosRouteImport } from './routes/painel.resultados'
import { Route as PainelRelatoriosRouteImport } from './routes/painel.relatorios'
import { Route as PainelDemandasRouteImport } from './routes/painel.demandas'
import { Route as PainelAssociadosRouteImport } from './routes/painel.associados'
import { Route as MarketingConteudosRouteImport } from './routes/marketing.conteudos'
import { Route as MarketingCalendarioRouteImport } from './routes/marketing.calendario'
import { Route as MarketingBancoMidiaRouteImport } from './routes/marketing.banco-midia'
import { Route as InteligenciaLeadsRouteImport } from './routes/inteligencia.leads'
import { Route as DashboardsWhatsappRouteImport } from './routes/dashboards.whatsapp'
import { Route as DashboardsOperacionalRouteImport } from './routes/dashboards.operacional'
import { Route as DashboardsMarketingRouteImport } from './routes/dashboards.marketing'
import { Route as DashboardsFinanceiroRouteImport } from './routes/dashboards.financeiro'
import { Route as DashboardsComercialRouteImport } from './routes/dashboards.comercial'
import { Route as DashboardsAdminRouteImport } from './routes/dashboards.admin'
import { Route as ControladoriaTesesRouteImport } from './routes/controladoria.teses'
import { Route as ControladoriaPrazosRouteImport } from './routes/controladoria.prazos'
import { Route as ControladoriaExcecoesRouteImport } from './routes/controladoria.excecoes'
import { Route as ControladoriaDistribuicaoRouteImport } from './routes/controladoria.distribuicao'
import { Route as ControladoriaDecisoesRouteImport } from './routes/controladoria.decisoes'
import { Route as ConfiguracoesWorkflowsRouteImport } from './routes/configuracoes.workflows'
import { Route as ConfiguracoesTiposTarefaRouteImport } from './routes/configuracoes.tipos-tarefa'
import { Route as ConfiguracoesIntegracoesRouteImport } from './routes/configuracoes.integracoes'
import { Route as ConfiguracoesImportacaoRouteImport } from './routes/configuracoes.importacao'
import { Route as ConfiguracoesCamposPersonalizadosRouteImport } from './routes/configuracoes.campos-personalizados'
import { Route as ComercialOportunidadesRouteImport } from './routes/comercial.oportunidades'
import { Route as ComercialLeadsRouteImport } from './routes/comercial.leads'
import { Route as ComercialFunilRouteImport } from './routes/comercial.funil'
import { Route as ComercialEmailMarketingRouteImport } from './routes/comercial.email-marketing'
import { Route as ComercialAssinaturasRouteImport } from './routes/comercial.assinaturas'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as CasosListaRouteImport } from './routes/casos.lista'
import { Route as CasosFinanceiroRouteImport } from './routes/casos.financeiro'
import { Route as CasosIdRouteImport } from './routes/casos.$id'
import { Route as ControladoriaDistribuicaoIndexRouteImport } from './routes/controladoria.distribuicao.index'
import { Route as CasosFinanceiroIndexRouteImport } from './routes/casos.financeiro.index'
import { Route as CasosIdIndexRouteImport } from './routes/casos.$id.index'
import { Route as WhatsappConversasIdRouteImport } from './routes/whatsapp.conversas.$id'
import { Route as PortalCasosIdRouteImport } from './routes/portal.casos.$id'
import { Route as ControladoriaDistribuicaoTiposTarefaRouteImport } from './routes/controladoria.distribuicao.tipos-tarefa'
import { Route as ControladoriaDistribuicaoTemasRouteImport } from './routes/controladoria.distribuicao.temas'
import { Route as ControladoriaDistribuicaoSimuladorRouteImport } from './routes/controladoria.distribuicao.simulador'
import { Route as ControladoriaDistribuicaoRelatorioRouteImport } from './routes/controladoria.distribuicao.relatorio'
import { Route as ControladoriaDistribuicaoListaRouteImport } from './routes/controladoria.distribuicao.lista'
import { Route as ControladoriaDistribuicaoKanbanRouteImport } from './routes/controladoria.distribuicao.kanban'
import { Route as ControladoriaDistribuicaoIndicadoresRouteImport } from './routes/controladoria.distribuicao.indicadores'
import { Route as ControladoriaDistribuicaoHistoricoTarefasRouteImport } from './routes/controladoria.distribuicao.historico-tarefas'
import { Route as ControladoriaDistribuicaoHistoricoAndamentosRouteImport } from './routes/controladoria.distribuicao.historico-andamentos'
import { Route as ControladoriaDistribuicaoHistoricoRouteImport } from './routes/controladoria.distribuicao.historico'
import { Route as ControladoriaDistribuicaoExecutoresRouteImport } from './routes/controladoria.distribuicao.executores'
import { Route as ControladoriaDistribuicaoExcecoesRouteImport } from './routes/controladoria.distribuicao.excecoes'
import { Route as ControladoriaDistribuicaoConfiguracaoRouteImport } from './routes/controladoria.distribuicao.configuracao'
import { Route as ControladoriaDistribuicaoCalendarioRouteImport } from './routes/controladoria.distribuicao.calendario'
import { Route as ControladoriaDistribuicaoAndamentosRouteImport } from './routes/controladoria.distribuicao.andamentos'
import { Route as ControladoriaDistribuicaoADistribuirRouteImport } from './routes/controladoria.distribuicao.a-distribuir'
import { Route as CasosFinanceiroInadimplenciaRouteImport } from './routes/casos.financeiro.inadimplencia'
import { Route as CasosFinanceiroCobrancasRouteImport } from './routes/casos.financeiro.cobrancas'
import { Route as CasosIdTermoRouteImport } from './routes/casos.$id.termo'
import { Route as CasosIdJudicialRouteImport } from './routes/casos.$id.judicial'
import { Route as CasosIdFinanceiroRouteImport } from './routes/casos.$id.financeiro'
import { Route as CasosIdDocumentosRouteImport } from './routes/casos.$id.documentos'
import { Route as ApiWebhooksZapsignRouteImport } from './routes/api.webhooks.zapsign'
import { Route as ApiWebhooksN8nRouteImport } from './routes/api.webhooks.n8n'
import { Route as ApiWebhooksAsaasRouteImport } from './routes/api.webhooks.asaas'
import { Route as ApiCronSyncContaazulRouteImport } from './routes/api.cron.sync-contaazul'
import { Route as ApiCronSyncAsaasRouteImport } from './routes/api.cron.sync-asaas'
import { Route as ApiCronDistribuicaoRouteImport } from './routes/api.cron.distribuicao'
import { Route as ApiCronDailyRouteImport } from './routes/api.cron.daily'
import { Route as ApiContaazulCallbackRouteImport } from './routes/api.contaazul.callback'
import { Route as CasosIdTermoElaborarRouteImport } from './routes/casos.$id.termo.elaborar'
import { Route as ApiClientsIdDocumentsIndexRouteImport } from './routes/api.clients.$id.documents.index'
import { Route as ApiServiceTypesIdTemplatesUploadRouteImport } from './routes/api.service-types.$id.templates.upload'
import { Route as ApiClientsIdDocumentsDocIdRouteImport } from './routes/api.clients.$id.documents.$docId'
import { Route as ApiCasesIdDocumentsUploadRouteImport } from './routes/api.cases.$id.documents.upload'
import { Route as ApiClientsIdDocumentsDocIdDownloadRouteImport } from './routes/api.clients.$id.documents.$docId.download'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioFinanceiroRoute = RelatorioFinanceiroRouteImport.update({
  id: '/relatorio-financeiro',
  path: '/relatorio-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciasRoute = ReferenciasRouteImport.update({
  id: '/referencias',
  path: '/referencias',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappIndexRoute = WhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeticionamentoIndexRoute = PeticionamentoIndexRouteImport.update({
  id: '/peticionamento/',
  path: '/peticionamento/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaIndexRoute = ControladoriaIndexRouteImport.update({
  id: '/controladoria/',
  path: '/controladoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ComercialIndexRoute = ComercialIndexRouteImport.update({
  id: '/comercial/',
  path: '/comercial/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIndexRoute = CasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappAgenteRoute = WhatsappAgenteRouteImport.update({
  id: '/whatsapp/agente',
  path: '/whatsapp/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPerfilRoute = PortalPerfilRouteImport.update({
  id: '/portal/perfil',
  path: '/portal/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMensagensRoute = PortalMensagensRouteImport.update({
  id: '/portal/mensagens',
  path: '/portal/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/portal/documentos',
  path: '/portal/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBoletosRoute = PortalBoletosRouteImport.update({
  id: '/portal/boletos',
  path: '/portal/boletos',
  getParentRoute: () => rootRouteImport,
} as any)
const PeticionamentoBancoPecasRoute =
  PeticionamentoBancoPecasRouteImport.update({
    id: '/peticionamento/banco-pecas',
    path: '/peticionamento/banco-pecas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PeticionamentoIdRoute = PeticionamentoIdRouteImport.update({
  id: '/peticionamento/$id',
  path: '/peticionamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelResultadosRoute = PainelResultadosRouteImport.update({
  id: '/painel/resultados',
  path: '/painel/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRelatoriosRoute = PainelRelatoriosRouteImport.update({
  id: '/painel/relatorios',
  path: '/painel/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelDemandasRoute = PainelDemandasRouteImport.update({
  id: '/painel/demandas',
  path: '/painel/demandas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAssociadosRoute = PainelAssociadosRouteImport.update({
  id: '/painel/associados',
  path: '/painel/associados',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingConteudosRoute = MarketingConteudosRouteImport.update({
  id: '/marketing/conteudos',
  path: '/marketing/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCalendarioRoute = MarketingCalendarioRouteImport.update({
  id: '/marketing/calendario',
  path: '/marketing/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingBancoMidiaRoute = MarketingBancoMidiaRouteImport.update({
  id: '/marketing/banco-midia',
  path: '/marketing/banco-midia',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaLeadsRoute = InteligenciaLeadsRouteImport.update({
  id: '/inteligencia/leads',
  path: '/inteligencia/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsWhatsappRoute = DashboardsWhatsappRouteImport.update({
  id: '/dashboards/whatsapp',
  path: '/dashboards/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsOperacionalRoute = DashboardsOperacionalRouteImport.update({
  id: '/dashboards/operacional',
  path: '/dashboards/operacional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsMarketingRoute = DashboardsMarketingRouteImport.update({
  id: '/dashboards/marketing',
  path: '/dashboards/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsFinanceiroRoute = DashboardsFinanceiroRouteImport.update({
  id: '/dashboards/financeiro',
  path: '/dashboards/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsComercialRoute = DashboardsComercialRouteImport.update({
  id: '/dashboards/comercial',
  path: '/dashboards/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsAdminRoute = DashboardsAdminRouteImport.update({
  id: '/dashboards/admin',
  path: '/dashboards/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaTesesRoute = ControladoriaTesesRouteImport.update({
  id: '/controladoria/teses',
  path: '/controladoria/teses',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaPrazosRoute = ControladoriaPrazosRouteImport.update({
  id: '/controladoria/prazos',
  path: '/controladoria/prazos',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaExcecoesRoute = ControladoriaExcecoesRouteImport.update({
  id: '/controladoria/excecoes',
  path: '/controladoria/excecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaDistribuicaoRoute =
  ControladoriaDistribuicaoRouteImport.update({
    id: '/controladoria/distribuicao',
    path: '/controladoria/distribuicao',
    getParentRoute: () => rootRouteImport,
  } as any)
const ControladoriaDecisoesRoute = ControladoriaDecisoesRouteImport.update({
  id: '/controladoria/decisoes',
  path: '/controladoria/decisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesWorkflowsRoute = ConfiguracoesWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesTiposTarefaRoute =
  ConfiguracoesTiposTarefaRouteImport.update({
    id: '/tipos-tarefa',
    path: '/tipos-tarefa',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesIntegracoesRoute =
  ConfiguracoesIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesImportacaoRoute = ConfiguracoesImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesCamposPersonalizadosRoute =
  ConfiguracoesCamposPersonalizadosRouteImport.update({
    id: '/campos-personalizados',
    path: '/campos-personalizados',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ComercialOportunidadesRoute = ComercialOportunidadesRouteImport.update({
  id: '/comercial/oportunidades',
  path: '/comercial/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialLeadsRoute = ComercialLeadsRouteImport.update({
  id: '/comercial/leads',
  path: '/comercial/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialFunilRoute = ComercialFunilRouteImport.update({
  id: '/comercial/funil',
  path: '/comercial/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialEmailMarketingRoute = ComercialEmailMarketingRouteImport.update({
  id: '/comercial/email-marketing',
  path: '/comercial/email-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialAssinaturasRoute = ComercialAssinaturasRouteImport.update({
  id: '/comercial/assinaturas',
  path: '/comercial/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosListaRoute = CasosListaRouteImport.update({
  id: '/casos/lista',
  path: '/casos/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosFinanceiroRoute = CasosFinanceiroRouteImport.update({
  id: '/casos/financeiro',
  path: '/casos/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIdRoute = CasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaDistribuicaoIndexRoute =
  ControladoriaDistribuicaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const CasosFinanceiroIndexRoute = CasosFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasosFinanceiroRoute,
} as any)
const CasosIdIndexRoute = CasosIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasosIdRoute,
} as any)
const WhatsappConversasIdRoute = WhatsappConversasIdRouteImport.update({
  id: '/whatsapp/conversas/$id',
  path: '/whatsapp/conversas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCasosIdRoute = PortalCasosIdRouteImport.update({
  id: '/portal/casos/$id',
  path: '/portal/casos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaDistribuicaoTiposTarefaRoute =
  ControladoriaDistribuicaoTiposTarefaRouteImport.update({
    id: '/tipos-tarefa',
    path: '/tipos-tarefa',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoTemasRoute =
  ControladoriaDistribuicaoTemasRouteImport.update({
    id: '/temas',
    path: '/temas',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoSimuladorRoute =
  ControladoriaDistribuicaoSimuladorRouteImport.update({
    id: '/simulador',
    path: '/simulador',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoRelatorioRoute =
  ControladoriaDistribuicaoRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoListaRoute =
  ControladoriaDistribuicaoListaRouteImport.update({
    id: '/lista',
    path: '/lista',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoKanbanRoute =
  ControladoriaDistribuicaoKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoIndicadoresRoute =
  ControladoriaDistribuicaoIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoHistoricoTarefasRoute =
  ControladoriaDistribuicaoHistoricoTarefasRouteImport.update({
    id: '/historico-tarefas',
    path: '/historico-tarefas',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoHistoricoAndamentosRoute =
  ControladoriaDistribuicaoHistoricoAndamentosRouteImport.update({
    id: '/historico-andamentos',
    path: '/historico-andamentos',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoHistoricoRoute =
  ControladoriaDistribuicaoHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoExecutoresRoute =
  ControladoriaDistribuicaoExecutoresRouteImport.update({
    id: '/executores',
    path: '/executores',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoExcecoesRoute =
  ControladoriaDistribuicaoExcecoesRouteImport.update({
    id: '/excecoes',
    path: '/excecoes',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoConfiguracaoRoute =
  ControladoriaDistribuicaoConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoCalendarioRoute =
  ControladoriaDistribuicaoCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoAndamentosRoute =
  ControladoriaDistribuicaoAndamentosRouteImport.update({
    id: '/andamentos',
    path: '/andamentos',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const ControladoriaDistribuicaoADistribuirRoute =
  ControladoriaDistribuicaoADistribuirRouteImport.update({
    id: '/a-distribuir',
    path: '/a-distribuir',
    getParentRoute: () => ControladoriaDistribuicaoRoute,
  } as any)
const CasosFinanceiroInadimplenciaRoute =
  CasosFinanceiroInadimplenciaRouteImport.update({
    id: '/inadimplencia',
    path: '/inadimplencia',
    getParentRoute: () => CasosFinanceiroRoute,
  } as any)
const CasosFinanceiroCobrancasRoute =
  CasosFinanceiroCobrancasRouteImport.update({
    id: '/cobrancas',
    path: '/cobrancas',
    getParentRoute: () => CasosFinanceiroRoute,
  } as any)
const CasosIdTermoRoute = CasosIdTermoRouteImport.update({
  id: '/termo',
  path: '/termo',
  getParentRoute: () => CasosIdRoute,
} as any)
const CasosIdJudicialRoute = CasosIdJudicialRouteImport.update({
  id: '/judicial',
  path: '/judicial',
  getParentRoute: () => CasosIdRoute,
} as any)
const CasosIdFinanceiroRoute = CasosIdFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => CasosIdRoute,
} as any)
const CasosIdDocumentosRoute = CasosIdDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => CasosIdRoute,
} as any)
const ApiWebhooksZapsignRoute = ApiWebhooksZapsignRouteImport.update({
  id: '/api/webhooks/zapsign',
  path: '/api/webhooks/zapsign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksN8nRoute = ApiWebhooksN8nRouteImport.update({
  id: '/api/webhooks/n8n',
  path: '/api/webhooks/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksAsaasRoute = ApiWebhooksAsaasRouteImport.update({
  id: '/api/webhooks/asaas',
  path: '/api/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncContaazulRoute = ApiCronSyncContaazulRouteImport.update({
  id: '/api/cron/sync-contaazul',
  path: '/api/cron/sync-contaazul',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncAsaasRoute = ApiCronSyncAsaasRouteImport.update({
  id: '/api/cron/sync-asaas',
  path: '/api/cron/sync-asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDistribuicaoRoute = ApiCronDistribuicaoRouteImport.update({
  id: '/api/cron/distribuicao',
  path: '/api/cron/distribuicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailyRoute = ApiCronDailyRouteImport.update({
  id: '/api/cron/daily',
  path: '/api/cron/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContaazulCallbackRoute = ApiContaazulCallbackRouteImport.update({
  id: '/api/contaazul/callback',
  path: '/api/contaazul/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIdTermoElaborarRoute = CasosIdTermoElaborarRouteImport.update({
  id: '/elaborar',
  path: '/elaborar',
  getParentRoute: () => CasosIdTermoRoute,
} as any)
const ApiClientsIdDocumentsIndexRoute =
  ApiClientsIdDocumentsIndexRouteImport.update({
    id: '/api/clients/$id/documents/',
    path: '/api/clients/$id/documents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiServiceTypesIdTemplatesUploadRoute =
  ApiServiceTypesIdTemplatesUploadRouteImport.update({
    id: '/api/service-types/$id/templates/upload',
    path: '/api/service-types/$id/templates/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiClientsIdDocumentsDocIdRoute =
  ApiClientsIdDocumentsDocIdRouteImport.update({
    id: '/api/clients/$id/documents/$docId',
    path: '/api/clients/$id/documents/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCasesIdDocumentsUploadRoute =
  ApiCasesIdDocumentsUploadRouteImport.update({
    id: '/api/cases/$id/documents/upload',
    path: '/api/cases/$id/documents/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiClientsIdDocumentsDocIdDownloadRoute =
  ApiClientsIdDocumentsDocIdDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiClientsIdDocumentsDocIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/definir-senha': typeof DefinirSenhaRoute
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/permissoes': typeof PermissoesRoute
  '/pipeline': typeof PipelineRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/referencias': typeof ReferenciasRoute
  '/relatorio-financeiro': typeof RelatorioFinanceiroRoute
  '/tarefas': typeof TarefasRoute
  '/casos/$id': typeof CasosIdRouteWithChildren
  '/casos/financeiro': typeof CasosFinanceiroRouteWithChildren
  '/casos/lista': typeof CasosListaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/assinaturas': typeof ComercialAssinaturasRoute
  '/comercial/email-marketing': typeof ComercialEmailMarketingRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/comercial/oportunidades': typeof ComercialOportunidadesRoute
  '/configuracoes/campos-personalizados': typeof ConfiguracoesCamposPersonalizadosRoute
  '/configuracoes/importacao': typeof ConfiguracoesImportacaoRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/tipos-tarefa': typeof ConfiguracoesTiposTarefaRoute
  '/configuracoes/workflows': typeof ConfiguracoesWorkflowsRoute
  '/controladoria/decisoes': typeof ControladoriaDecisoesRoute
  '/controladoria/distribuicao': typeof ControladoriaDistribuicaoRouteWithChildren
  '/controladoria/excecoes': typeof ControladoriaExcecoesRoute
  '/controladoria/prazos': typeof ControladoriaPrazosRoute
  '/controladoria/teses': typeof ControladoriaTesesRoute
  '/dashboards/admin': typeof DashboardsAdminRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/marketing': typeof DashboardsMarketingRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/dashboards/whatsapp': typeof DashboardsWhatsappRoute
  '/inteligencia/leads': typeof InteligenciaLeadsRoute
  '/marketing/banco-midia': typeof MarketingBancoMidiaRoute
  '/marketing/calendario': typeof MarketingCalendarioRoute
  '/marketing/conteudos': typeof MarketingConteudosRoute
  '/painel/associados': typeof PainelAssociadosRoute
  '/painel/demandas': typeof PainelDemandasRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/resultados': typeof PainelResultadosRoute
  '/peticionamento/$id': typeof PeticionamentoIdRoute
  '/peticionamento/banco-pecas': typeof PeticionamentoBancoPecasRoute
  '/portal/boletos': typeof PortalBoletosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/whatsapp/agente': typeof WhatsappAgenteRoute
  '/casos/': typeof CasosIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/controladoria/': typeof ControladoriaIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/peticionamento/': typeof PeticionamentoIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/whatsapp/': typeof WhatsappIndexRoute
  '/api/contaazul/callback': typeof ApiContaazulCallbackRoute
  '/api/cron/daily': typeof ApiCronDailyRoute
  '/api/cron/distribuicao': typeof ApiCronDistribuicaoRoute
  '/api/cron/sync-asaas': typeof ApiCronSyncAsaasRoute
  '/api/cron/sync-contaazul': typeof ApiCronSyncContaazulRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/api/webhooks/n8n': typeof ApiWebhooksN8nRoute
  '/api/webhooks/zapsign': typeof ApiWebhooksZapsignRoute
  '/casos/$id/documentos': typeof CasosIdDocumentosRoute
  '/casos/$id/financeiro': typeof CasosIdFinanceiroRoute
  '/casos/$id/judicial': typeof CasosIdJudicialRoute
  '/casos/$id/termo': typeof CasosIdTermoRouteWithChildren
  '/casos/financeiro/cobrancas': typeof CasosFinanceiroCobrancasRoute
  '/casos/financeiro/inadimplencia': typeof CasosFinanceiroInadimplenciaRoute
  '/controladoria/distribuicao/a-distribuir': typeof ControladoriaDistribuicaoADistribuirRoute
  '/controladoria/distribuicao/andamentos': typeof ControladoriaDistribuicaoAndamentosRoute
  '/controladoria/distribuicao/calendario': typeof ControladoriaDistribuicaoCalendarioRoute
  '/controladoria/distribuicao/configuracao': typeof ControladoriaDistribuicaoConfiguracaoRoute
  '/controladoria/distribuicao/excecoes': typeof ControladoriaDistribuicaoExcecoesRoute
  '/controladoria/distribuicao/executores': typeof ControladoriaDistribuicaoExecutoresRoute
  '/controladoria/distribuicao/historico': typeof ControladoriaDistribuicaoHistoricoRoute
  '/controladoria/distribuicao/historico-andamentos': typeof ControladoriaDistribuicaoHistoricoAndamentosRoute
  '/controladoria/distribuicao/historico-tarefas': typeof ControladoriaDistribuicaoHistoricoTarefasRoute
  '/controladoria/distribuicao/indicadores': typeof ControladoriaDistribuicaoIndicadoresRoute
  '/controladoria/distribuicao/kanban': typeof ControladoriaDistribuicaoKanbanRoute
  '/controladoria/distribuicao/lista': typeof ControladoriaDistribuicaoListaRoute
  '/controladoria/distribuicao/relatorio': typeof ControladoriaDistribuicaoRelatorioRoute
  '/controladoria/distribuicao/simulador': typeof ControladoriaDistribuicaoSimuladorRoute
  '/controladoria/distribuicao/temas': typeof ControladoriaDistribuicaoTemasRoute
  '/controladoria/distribuicao/tipos-tarefa': typeof ControladoriaDistribuicaoTiposTarefaRoute
  '/portal/casos/$id': typeof PortalCasosIdRoute
  '/whatsapp/conversas/$id': typeof WhatsappConversasIdRoute
  '/casos/$id/': typeof CasosIdIndexRoute
  '/casos/financeiro/': typeof CasosFinanceiroIndexRoute
  '/controladoria/distribuicao/': typeof ControladoriaDistribuicaoIndexRoute
  '/casos/$id/termo/elaborar': typeof CasosIdTermoElaborarRoute
  '/api/cases/$id/documents/upload': typeof ApiCasesIdDocumentsUploadRoute
  '/api/clients/$id/documents/$docId': typeof ApiClientsIdDocumentsDocIdRouteWithChildren
  '/api/service-types/$id/templates/upload': typeof ApiServiceTypesIdTemplatesUploadRoute
  '/api/clients/$id/documents/': typeof ApiClientsIdDocumentsIndexRoute
  '/api/clients/$id/documents/$docId/download': typeof ApiClientsIdDocumentsDocIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/permissoes': typeof PermissoesRoute
  '/pipeline': typeof PipelineRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/referencias': typeof ReferenciasRoute
  '/relatorio-financeiro': typeof RelatorioFinanceiroRoute
  '/tarefas': typeof TarefasRoute
  '/casos/lista': typeof CasosListaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/assinaturas': typeof ComercialAssinaturasRoute
  '/comercial/email-marketing': typeof ComercialEmailMarketingRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/comercial/oportunidades': typeof ComercialOportunidadesRoute
  '/configuracoes/campos-personalizados': typeof ConfiguracoesCamposPersonalizadosRoute
  '/configuracoes/importacao': typeof ConfiguracoesImportacaoRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/tipos-tarefa': typeof ConfiguracoesTiposTarefaRoute
  '/configuracoes/workflows': typeof ConfiguracoesWorkflowsRoute
  '/controladoria/decisoes': typeof ControladoriaDecisoesRoute
  '/controladoria/excecoes': typeof ControladoriaExcecoesRoute
  '/controladoria/prazos': typeof ControladoriaPrazosRoute
  '/controladoria/teses': typeof ControladoriaTesesRoute
  '/dashboards/admin': typeof DashboardsAdminRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/marketing': typeof DashboardsMarketingRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/dashboards/whatsapp': typeof DashboardsWhatsappRoute
  '/inteligencia/leads': typeof InteligenciaLeadsRoute
  '/marketing/banco-midia': typeof MarketingBancoMidiaRoute
  '/marketing/calendario': typeof MarketingCalendarioRoute
  '/marketing/conteudos': typeof MarketingConteudosRoute
  '/painel/associados': typeof PainelAssociadosRoute
  '/painel/demandas': typeof PainelDemandasRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/resultados': typeof PainelResultadosRoute
  '/peticionamento/$id': typeof PeticionamentoIdRoute
  '/peticionamento/banco-pecas': typeof PeticionamentoBancoPecasRoute
  '/portal/boletos': typeof PortalBoletosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/whatsapp/agente': typeof WhatsappAgenteRoute
  '/casos': typeof CasosIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/comercial': typeof ComercialIndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/controladoria': typeof ControladoriaIndexRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/painel': typeof PainelIndexRoute
  '/peticionamento': typeof PeticionamentoIndexRoute
  '/portal': typeof PortalIndexRoute
  '/whatsapp': typeof WhatsappIndexRoute
  '/api/contaazul/callback': typeof ApiContaazulCallbackRoute
  '/api/cron/daily': typeof ApiCronDailyRoute
  '/api/cron/distribuicao': typeof ApiCronDistribuicaoRoute
  '/api/cron/sync-asaas': typeof ApiCronSyncAsaasRoute
  '/api/cron/sync-contaazul': typeof ApiCronSyncContaazulRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/api/webhooks/n8n': typeof ApiWebhooksN8nRoute
  '/api/webhooks/zapsign': typeof ApiWebhooksZapsignRoute
  '/casos/$id/documentos': typeof CasosIdDocumentosRoute
  '/casos/$id/financeiro': typeof CasosIdFinanceiroRoute
  '/casos/$id/judicial': typeof CasosIdJudicialRoute
  '/casos/$id/termo': typeof CasosIdTermoRouteWithChildren
  '/casos/financeiro/cobrancas': typeof CasosFinanceiroCobrancasRoute
  '/casos/financeiro/inadimplencia': typeof CasosFinanceiroInadimplenciaRoute
  '/controladoria/distribuicao/a-distribuir': typeof ControladoriaDistribuicaoADistribuirRoute
  '/controladoria/distribuicao/andamentos': typeof ControladoriaDistribuicaoAndamentosRoute
  '/controladoria/distribuicao/calendario': typeof ControladoriaDistribuicaoCalendarioRoute
  '/controladoria/distribuicao/configuracao': typeof ControladoriaDistribuicaoConfiguracaoRoute
  '/controladoria/distribuicao/excecoes': typeof ControladoriaDistribuicaoExcecoesRoute
  '/controladoria/distribuicao/executores': typeof ControladoriaDistribuicaoExecutoresRoute
  '/controladoria/distribuicao/historico': typeof ControladoriaDistribuicaoHistoricoRoute
  '/controladoria/distribuicao/historico-andamentos': typeof ControladoriaDistribuicaoHistoricoAndamentosRoute
  '/controladoria/distribuicao/historico-tarefas': typeof ControladoriaDistribuicaoHistoricoTarefasRoute
  '/controladoria/distribuicao/indicadores': typeof ControladoriaDistribuicaoIndicadoresRoute
  '/controladoria/distribuicao/kanban': typeof ControladoriaDistribuicaoKanbanRoute
  '/controladoria/distribuicao/lista': typeof ControladoriaDistribuicaoListaRoute
  '/controladoria/distribuicao/relatorio': typeof ControladoriaDistribuicaoRelatorioRoute
  '/controladoria/distribuicao/simulador': typeof ControladoriaDistribuicaoSimuladorRoute
  '/controladoria/distribuicao/temas': typeof ControladoriaDistribuicaoTemasRoute
  '/controladoria/distribuicao/tipos-tarefa': typeof ControladoriaDistribuicaoTiposTarefaRoute
  '/portal/casos/$id': typeof PortalCasosIdRoute
  '/whatsapp/conversas/$id': typeof WhatsappConversasIdRoute
  '/casos/$id': typeof CasosIdIndexRoute
  '/casos/financeiro': typeof CasosFinanceiroIndexRoute
  '/controladoria/distribuicao': typeof ControladoriaDistribuicaoIndexRoute
  '/casos/$id/termo/elaborar': typeof CasosIdTermoElaborarRoute
  '/api/cases/$id/documents/upload': typeof ApiCasesIdDocumentsUploadRoute
  '/api/clients/$id/documents/$docId': typeof ApiClientsIdDocumentsDocIdRouteWithChildren
  '/api/service-types/$id/templates/upload': typeof ApiServiceTypesIdTemplatesUploadRoute
  '/api/clients/$id/documents': typeof ApiClientsIdDocumentsIndexRoute
  '/api/clients/$id/documents/$docId/download': typeof ApiClientsIdDocumentsDocIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/definir-senha': typeof DefinirSenhaRoute
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/permissoes': typeof PermissoesRoute
  '/pipeline': typeof PipelineRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/referencias': typeof ReferenciasRoute
  '/relatorio-financeiro': typeof RelatorioFinanceiroRoute
  '/tarefas': typeof TarefasRoute
  '/casos/$id': typeof CasosIdRouteWithChildren
  '/casos/financeiro': typeof CasosFinanceiroRouteWithChildren
  '/casos/lista': typeof CasosListaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/assinaturas': typeof ComercialAssinaturasRoute
  '/comercial/email-marketing': typeof ComercialEmailMarketingRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/comercial/oportunidades': typeof ComercialOportunidadesRoute
  '/configuracoes/campos-personalizados': typeof ConfiguracoesCamposPersonalizadosRoute
  '/configuracoes/importacao': typeof ConfiguracoesImportacaoRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/tipos-tarefa': typeof ConfiguracoesTiposTarefaRoute
  '/configuracoes/workflows': typeof ConfiguracoesWorkflowsRoute
  '/controladoria/decisoes': typeof ControladoriaDecisoesRoute
  '/controladoria/distribuicao': typeof ControladoriaDistribuicaoRouteWithChildren
  '/controladoria/excecoes': typeof ControladoriaExcecoesRoute
  '/controladoria/prazos': typeof ControladoriaPrazosRoute
  '/controladoria/teses': typeof ControladoriaTesesRoute
  '/dashboards/admin': typeof DashboardsAdminRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/marketing': typeof DashboardsMarketingRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/dashboards/whatsapp': typeof DashboardsWhatsappRoute
  '/inteligencia/leads': typeof InteligenciaLeadsRoute
  '/marketing/banco-midia': typeof MarketingBancoMidiaRoute
  '/marketing/calendario': typeof MarketingCalendarioRoute
  '/marketing/conteudos': typeof MarketingConteudosRoute
  '/painel/associados': typeof PainelAssociadosRoute
  '/painel/demandas': typeof PainelDemandasRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/resultados': typeof PainelResultadosRoute
  '/peticionamento/$id': typeof PeticionamentoIdRoute
  '/peticionamento/banco-pecas': typeof PeticionamentoBancoPecasRoute
  '/portal/boletos': typeof PortalBoletosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/whatsapp/agente': typeof WhatsappAgenteRoute
  '/casos/': typeof CasosIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/controladoria/': typeof ControladoriaIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/peticionamento/': typeof PeticionamentoIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/whatsapp/': typeof WhatsappIndexRoute
  '/api/contaazul/callback': typeof ApiContaazulCallbackRoute
  '/api/cron/daily': typeof ApiCronDailyRoute
  '/api/cron/distribuicao': typeof ApiCronDistribuicaoRoute
  '/api/cron/sync-asaas': typeof ApiCronSyncAsaasRoute
  '/api/cron/sync-contaazul': typeof ApiCronSyncContaazulRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/api/webhooks/n8n': typeof ApiWebhooksN8nRoute
  '/api/webhooks/zapsign': typeof ApiWebhooksZapsignRoute
  '/casos/$id/documentos': typeof CasosIdDocumentosRoute
  '/casos/$id/financeiro': typeof CasosIdFinanceiroRoute
  '/casos/$id/judicial': typeof CasosIdJudicialRoute
  '/casos/$id/termo': typeof CasosIdTermoRouteWithChildren
  '/casos/financeiro/cobrancas': typeof CasosFinanceiroCobrancasRoute
  '/casos/financeiro/inadimplencia': typeof CasosFinanceiroInadimplenciaRoute
  '/controladoria/distribuicao/a-distribuir': typeof ControladoriaDistribuicaoADistribuirRoute
  '/controladoria/distribuicao/andamentos': typeof ControladoriaDistribuicaoAndamentosRoute
  '/controladoria/distribuicao/calendario': typeof ControladoriaDistribuicaoCalendarioRoute
  '/controladoria/distribuicao/configuracao': typeof ControladoriaDistribuicaoConfiguracaoRoute
  '/controladoria/distribuicao/excecoes': typeof ControladoriaDistribuicaoExcecoesRoute
  '/controladoria/distribuicao/executores': typeof ControladoriaDistribuicaoExecutoresRoute
  '/controladoria/distribuicao/historico': typeof ControladoriaDistribuicaoHistoricoRoute
  '/controladoria/distribuicao/historico-andamentos': typeof ControladoriaDistribuicaoHistoricoAndamentosRoute
  '/controladoria/distribuicao/historico-tarefas': typeof ControladoriaDistribuicaoHistoricoTarefasRoute
  '/controladoria/distribuicao/indicadores': typeof ControladoriaDistribuicaoIndicadoresRoute
  '/controladoria/distribuicao/kanban': typeof ControladoriaDistribuicaoKanbanRoute
  '/controladoria/distribuicao/lista': typeof ControladoriaDistribuicaoListaRoute
  '/controladoria/distribuicao/relatorio': typeof ControladoriaDistribuicaoRelatorioRoute
  '/controladoria/distribuicao/simulador': typeof ControladoriaDistribuicaoSimuladorRoute
  '/controladoria/distribuicao/temas': typeof ControladoriaDistribuicaoTemasRoute
  '/controladoria/distribuicao/tipos-tarefa': typeof ControladoriaDistribuicaoTiposTarefaRoute
  '/portal/casos/$id': typeof PortalCasosIdRoute
  '/whatsapp/conversas/$id': typeof WhatsappConversasIdRoute
  '/casos/$id/': typeof CasosIdIndexRoute
  '/casos/financeiro/': typeof CasosFinanceiroIndexRoute
  '/controladoria/distribuicao/': typeof ControladoriaDistribuicaoIndexRoute
  '/casos/$id/termo/elaborar': typeof CasosIdTermoElaborarRoute
  '/api/cases/$id/documents/upload': typeof ApiCasesIdDocumentsUploadRoute
  '/api/clients/$id/documents/$docId': typeof ApiClientsIdDocumentsDocIdRouteWithChildren
  '/api/service-types/$id/templates/upload': typeof ApiServiceTypesIdTemplatesUploadRoute
  '/api/clients/$id/documents/': typeof ApiClientsIdDocumentsIndexRoute
  '/api/clients/$id/documents/$docId/download': typeof ApiClientsIdDocumentsDocIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/definir-senha'
    | '/design-system'
    | '/entrar'
    | '/hoje'
    | '/login'
    | '/modelos'
    | '/nova-senha'
    | '/permissoes'
    | '/pipeline'
    | '/recuperar-senha'
    | '/referencias'
    | '/relatorio-financeiro'
    | '/tarefas'
    | '/casos/$id'
    | '/casos/financeiro'
    | '/casos/lista'
    | '/clientes/$id'
    | '/comercial/assinaturas'
    | '/comercial/email-marketing'
    | '/comercial/funil'
    | '/comercial/leads'
    | '/comercial/oportunidades'
    | '/configuracoes/campos-personalizados'
    | '/configuracoes/importacao'
    | '/configuracoes/integracoes'
    | '/configuracoes/tipos-tarefa'
    | '/configuracoes/workflows'
    | '/controladoria/decisoes'
    | '/controladoria/distribuicao'
    | '/controladoria/excecoes'
    | '/controladoria/prazos'
    | '/controladoria/teses'
    | '/dashboards/admin'
    | '/dashboards/comercial'
    | '/dashboards/financeiro'
    | '/dashboards/marketing'
    | '/dashboards/operacional'
    | '/dashboards/whatsapp'
    | '/inteligencia/leads'
    | '/marketing/banco-midia'
    | '/marketing/calendario'
    | '/marketing/conteudos'
    | '/painel/associados'
    | '/painel/demandas'
    | '/painel/relatorios'
    | '/painel/resultados'
    | '/peticionamento/$id'
    | '/peticionamento/banco-pecas'
    | '/portal/boletos'
    | '/portal/documentos'
    | '/portal/mensagens'
    | '/portal/perfil'
    | '/whatsapp/agente'
    | '/casos/'
    | '/clientes/'
    | '/comercial/'
    | '/configuracoes/'
    | '/controladoria/'
    | '/dashboards/'
    | '/marketing/'
    | '/painel/'
    | '/peticionamento/'
    | '/portal/'
    | '/whatsapp/'
    | '/api/contaazul/callback'
    | '/api/cron/daily'
    | '/api/cron/distribuicao'
    | '/api/cron/sync-asaas'
    | '/api/cron/sync-contaazul'
    | '/api/webhooks/asaas'
    | '/api/webhooks/n8n'
    | '/api/webhooks/zapsign'
    | '/casos/$id/documentos'
    | '/casos/$id/financeiro'
    | '/casos/$id/judicial'
    | '/casos/$id/termo'
    | '/casos/financeiro/cobrancas'
    | '/casos/financeiro/inadimplencia'
    | '/controladoria/distribuicao/a-distribuir'
    | '/controladoria/distribuicao/andamentos'
    | '/controladoria/distribuicao/calendario'
    | '/controladoria/distribuicao/configuracao'
    | '/controladoria/distribuicao/excecoes'
    | '/controladoria/distribuicao/executores'
    | '/controladoria/distribuicao/historico'
    | '/controladoria/distribuicao/historico-andamentos'
    | '/controladoria/distribuicao/historico-tarefas'
    | '/controladoria/distribuicao/indicadores'
    | '/controladoria/distribuicao/kanban'
    | '/controladoria/distribuicao/lista'
    | '/controladoria/distribuicao/relatorio'
    | '/controladoria/distribuicao/simulador'
    | '/controladoria/distribuicao/temas'
    | '/controladoria/distribuicao/tipos-tarefa'
    | '/portal/casos/$id'
    | '/whatsapp/conversas/$id'
    | '/casos/$id/'
    | '/casos/financeiro/'
    | '/controladoria/distribuicao/'
    | '/casos/$id/termo/elaborar'
    | '/api/cases/$id/documents/upload'
    | '/api/clients/$id/documents/$docId'
    | '/api/service-types/$id/templates/upload'
    | '/api/clients/$id/documents/'
    | '/api/clients/$id/documents/$docId/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/definir-senha'
    | '/design-system'
    | '/entrar'
    | '/hoje'
    | '/login'
    | '/modelos'
    | '/nova-senha'
    | '/permissoes'
    | '/pipeline'
    | '/recuperar-senha'
    | '/referencias'
    | '/relatorio-financeiro'
    | '/tarefas'
    | '/casos/lista'
    | '/clientes/$id'
    | '/comercial/assinaturas'
    | '/comercial/email-marketing'
    | '/comercial/funil'
    | '/comercial/leads'
    | '/comercial/oportunidades'
    | '/configuracoes/campos-personalizados'
    | '/configuracoes/importacao'
    | '/configuracoes/integracoes'
    | '/configuracoes/tipos-tarefa'
    | '/configuracoes/workflows'
    | '/controladoria/decisoes'
    | '/controladoria/excecoes'
    | '/controladoria/prazos'
    | '/controladoria/teses'
    | '/dashboards/admin'
    | '/dashboards/comercial'
    | '/dashboards/financeiro'
    | '/dashboards/marketing'
    | '/dashboards/operacional'
    | '/dashboards/whatsapp'
    | '/inteligencia/leads'
    | '/marketing/banco-midia'
    | '/marketing/calendario'
    | '/marketing/conteudos'
    | '/painel/associados'
    | '/painel/demandas'
    | '/painel/relatorios'
    | '/painel/resultados'
    | '/peticionamento/$id'
    | '/peticionamento/banco-pecas'
    | '/portal/boletos'
    | '/portal/documentos'
    | '/portal/mensagens'
    | '/portal/perfil'
    | '/whatsapp/agente'
    | '/casos'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/controladoria'
    | '/dashboards'
    | '/marketing'
    | '/painel'
    | '/peticionamento'
    | '/portal'
    | '/whatsapp'
    | '/api/contaazul/callback'
    | '/api/cron/daily'
    | '/api/cron/distribuicao'
    | '/api/cron/sync-asaas'
    | '/api/cron/sync-contaazul'
    | '/api/webhooks/asaas'
    | '/api/webhooks/n8n'
    | '/api/webhooks/zapsign'
    | '/casos/$id/documentos'
    | '/casos/$id/financeiro'
    | '/casos/$id/judicial'
    | '/casos/$id/termo'
    | '/casos/financeiro/cobrancas'
    | '/casos/financeiro/inadimplencia'
    | '/controladoria/distribuicao/a-distribuir'
    | '/controladoria/distribuicao/andamentos'
    | '/controladoria/distribuicao/calendario'
    | '/controladoria/distribuicao/configuracao'
    | '/controladoria/distribuicao/excecoes'
    | '/controladoria/distribuicao/executores'
    | '/controladoria/distribuicao/historico'
    | '/controladoria/distribuicao/historico-andamentos'
    | '/controladoria/distribuicao/historico-tarefas'
    | '/controladoria/distribuicao/indicadores'
    | '/controladoria/distribuicao/kanban'
    | '/controladoria/distribuicao/lista'
    | '/controladoria/distribuicao/relatorio'
    | '/controladoria/distribuicao/simulador'
    | '/controladoria/distribuicao/temas'
    | '/controladoria/distribuicao/tipos-tarefa'
    | '/portal/casos/$id'
    | '/whatsapp/conversas/$id'
    | '/casos/$id'
    | '/casos/financeiro'
    | '/controladoria/distribuicao'
    | '/casos/$id/termo/elaborar'
    | '/api/cases/$id/documents/upload'
    | '/api/clients/$id/documents/$docId'
    | '/api/service-types/$id/templates/upload'
    | '/api/clients/$id/documents'
    | '/api/clients/$id/documents/$docId/download'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/definir-senha'
    | '/design-system'
    | '/entrar'
    | '/hoje'
    | '/login'
    | '/modelos'
    | '/nova-senha'
    | '/permissoes'
    | '/pipeline'
    | '/recuperar-senha'
    | '/referencias'
    | '/relatorio-financeiro'
    | '/tarefas'
    | '/casos/$id'
    | '/casos/financeiro'
    | '/casos/lista'
    | '/clientes/$id'
    | '/comercial/assinaturas'
    | '/comercial/email-marketing'
    | '/comercial/funil'
    | '/comercial/leads'
    | '/comercial/oportunidades'
    | '/configuracoes/campos-personalizados'
    | '/configuracoes/importacao'
    | '/configuracoes/integracoes'
    | '/configuracoes/tipos-tarefa'
    | '/configuracoes/workflows'
    | '/controladoria/decisoes'
    | '/controladoria/distribuicao'
    | '/controladoria/excecoes'
    | '/controladoria/prazos'
    | '/controladoria/teses'
    | '/dashboards/admin'
    | '/dashboards/comercial'
    | '/dashboards/financeiro'
    | '/dashboards/marketing'
    | '/dashboards/operacional'
    | '/dashboards/whatsapp'
    | '/inteligencia/leads'
    | '/marketing/banco-midia'
    | '/marketing/calendario'
    | '/marketing/conteudos'
    | '/painel/associados'
    | '/painel/demandas'
    | '/painel/relatorios'
    | '/painel/resultados'
    | '/peticionamento/$id'
    | '/peticionamento/banco-pecas'
    | '/portal/boletos'
    | '/portal/documentos'
    | '/portal/mensagens'
    | '/portal/perfil'
    | '/whatsapp/agente'
    | '/casos/'
    | '/clientes/'
    | '/comercial/'
    | '/configuracoes/'
    | '/controladoria/'
    | '/dashboards/'
    | '/marketing/'
    | '/painel/'
    | '/peticionamento/'
    | '/portal/'
    | '/whatsapp/'
    | '/api/contaazul/callback'
    | '/api/cron/daily'
    | '/api/cron/distribuicao'
    | '/api/cron/sync-asaas'
    | '/api/cron/sync-contaazul'
    | '/api/webhooks/asaas'
    | '/api/webhooks/n8n'
    | '/api/webhooks/zapsign'
    | '/casos/$id/documentos'
    | '/casos/$id/financeiro'
    | '/casos/$id/judicial'
    | '/casos/$id/termo'
    | '/casos/financeiro/cobrancas'
    | '/casos/financeiro/inadimplencia'
    | '/controladoria/distribuicao/a-distribuir'
    | '/controladoria/distribuicao/andamentos'
    | '/controladoria/distribuicao/calendario'
    | '/controladoria/distribuicao/configuracao'
    | '/controladoria/distribuicao/excecoes'
    | '/controladoria/distribuicao/executores'
    | '/controladoria/distribuicao/historico'
    | '/controladoria/distribuicao/historico-andamentos'
    | '/controladoria/distribuicao/historico-tarefas'
    | '/controladoria/distribuicao/indicadores'
    | '/controladoria/distribuicao/kanban'
    | '/controladoria/distribuicao/lista'
    | '/controladoria/distribuicao/relatorio'
    | '/controladoria/distribuicao/simulador'
    | '/controladoria/distribuicao/temas'
    | '/controladoria/distribuicao/tipos-tarefa'
    | '/portal/casos/$id'
    | '/whatsapp/conversas/$id'
    | '/casos/$id/'
    | '/casos/financeiro/'
    | '/controladoria/distribuicao/'
    | '/casos/$id/termo/elaborar'
    | '/api/cases/$id/documents/upload'
    | '/api/clients/$id/documents/$docId'
    | '/api/service-types/$id/templates/upload'
    | '/api/clients/$id/documents/'
    | '/api/clients/$id/documents/$docId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EntrarRoute: typeof EntrarRoute
  HojeRoute: typeof HojeRoute
  LoginRoute: typeof LoginRoute
  ModelosRoute: typeof ModelosRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  PermissoesRoute: typeof PermissoesRoute
  PipelineRoute: typeof PipelineRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ReferenciasRoute: typeof ReferenciasRoute
  RelatorioFinanceiroRoute: typeof RelatorioFinanceiroRoute
  TarefasRoute: typeof TarefasRoute
  CasosIdRoute: typeof CasosIdRouteWithChildren
  CasosFinanceiroRoute: typeof CasosFinanceiroRouteWithChildren
  CasosListaRoute: typeof CasosListaRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ComercialAssinaturasRoute: typeof ComercialAssinaturasRoute
  ComercialEmailMarketingRoute: typeof ComercialEmailMarketingRoute
  ComercialFunilRoute: typeof ComercialFunilRoute
  ComercialLeadsRoute: typeof ComercialLeadsRoute
  ComercialOportunidadesRoute: typeof ComercialOportunidadesRoute
  ControladoriaDecisoesRoute: typeof ControladoriaDecisoesRoute
  ControladoriaDistribuicaoRoute: typeof ControladoriaDistribuicaoRouteWithChildren
  ControladoriaExcecoesRoute: typeof ControladoriaExcecoesRoute
  ControladoriaPrazosRoute: typeof ControladoriaPrazosRoute
  ControladoriaTesesRoute: typeof ControladoriaTesesRoute
  DashboardsAdminRoute: typeof DashboardsAdminRoute
  DashboardsComercialRoute: typeof DashboardsComercialRoute
  DashboardsFinanceiroRoute: typeof DashboardsFinanceiroRoute
  DashboardsMarketingRoute: typeof DashboardsMarketingRoute
  DashboardsOperacionalRoute: typeof DashboardsOperacionalRoute
  DashboardsWhatsappRoute: typeof DashboardsWhatsappRoute
  InteligenciaLeadsRoute: typeof InteligenciaLeadsRoute
  MarketingBancoMidiaRoute: typeof MarketingBancoMidiaRoute
  MarketingCalendarioRoute: typeof MarketingCalendarioRoute
  MarketingConteudosRoute: typeof MarketingConteudosRoute
  PainelAssociadosRoute: typeof PainelAssociadosRoute
  PainelDemandasRoute: typeof PainelDemandasRoute
  PainelRelatoriosRoute: typeof PainelRelatoriosRoute
  PainelResultadosRoute: typeof PainelResultadosRoute
  PeticionamentoIdRoute: typeof PeticionamentoIdRoute
  PeticionamentoBancoPecasRoute: typeof PeticionamentoBancoPecasRoute
  PortalBoletosRoute: typeof PortalBoletosRoute
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalMensagensRoute: typeof PortalMensagensRoute
  PortalPerfilRoute: typeof PortalPerfilRoute
  WhatsappAgenteRoute: typeof WhatsappAgenteRoute
  CasosIndexRoute: typeof CasosIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ComercialIndexRoute: typeof ComercialIndexRoute
  ControladoriaIndexRoute: typeof ControladoriaIndexRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PeticionamentoIndexRoute: typeof PeticionamentoIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  WhatsappIndexRoute: typeof WhatsappIndexRoute
  ApiContaazulCallbackRoute: typeof ApiContaazulCallbackRoute
  ApiCronDailyRoute: typeof ApiCronDailyRoute
  ApiCronDistribuicaoRoute: typeof ApiCronDistribuicaoRoute
  ApiCronSyncAsaasRoute: typeof ApiCronSyncAsaasRoute
  ApiCronSyncContaazulRoute: typeof ApiCronSyncContaazulRoute
  ApiWebhooksAsaasRoute: typeof ApiWebhooksAsaasRoute
  ApiWebhooksN8nRoute: typeof ApiWebhooksN8nRoute
  ApiWebhooksZapsignRoute: typeof ApiWebhooksZapsignRoute
  PortalCasosIdRoute: typeof PortalCasosIdRoute
  WhatsappConversasIdRoute: typeof WhatsappConversasIdRoute
  ApiCasesIdDocumentsUploadRoute: typeof ApiCasesIdDocumentsUploadRoute
  ApiClientsIdDocumentsDocIdRoute: typeof ApiClientsIdDocumentsDocIdRouteWithChildren
  ApiServiceTypesIdTemplatesUploadRoute: typeof ApiServiceTypesIdTemplatesUploadRoute
  ApiClientsIdDocumentsIndexRoute: typeof ApiClientsIdDocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-financeiro': {
      id: '/relatorio-financeiro'
      path: '/relatorio-financeiro'
      fullPath: '/relatorio-financeiro'
      preLoaderRoute: typeof RelatorioFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencias': {
      id: '/referencias'
      path: '/referencias'
      fullPath: '/referencias'
      preLoaderRoute: typeof ReferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/': {
      id: '/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof WhatsappIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peticionamento/': {
      id: '/peticionamento/'
      path: '/peticionamento'
      fullPath: '/peticionamento/'
      preLoaderRoute: typeof PeticionamentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/': {
      id: '/controladoria/'
      path: '/controladoria'
      fullPath: '/controladoria/'
      preLoaderRoute: typeof ControladoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/comercial/': {
      id: '/comercial/'
      path: '/comercial'
      fullPath: '/comercial/'
      preLoaderRoute: typeof ComercialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/': {
      id: '/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof CasosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/agente': {
      id: '/whatsapp/agente'
      path: '/whatsapp/agente'
      fullPath: '/whatsapp/agente'
      preLoaderRoute: typeof WhatsappAgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/perfil': {
      id: '/portal/perfil'
      path: '/portal/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof PortalPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/mensagens': {
      id: '/portal/mensagens'
      path: '/portal/mensagens'
      fullPath: '/portal/mensagens'
      preLoaderRoute: typeof PortalMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/portal/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/boletos': {
      id: '/portal/boletos'
      path: '/portal/boletos'
      fullPath: '/portal/boletos'
      preLoaderRoute: typeof PortalBoletosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peticionamento/banco-pecas': {
      id: '/peticionamento/banco-pecas'
      path: '/peticionamento/banco-pecas'
      fullPath: '/peticionamento/banco-pecas'
      preLoaderRoute: typeof PeticionamentoBancoPecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peticionamento/$id': {
      id: '/peticionamento/$id'
      path: '/peticionamento/$id'
      fullPath: '/peticionamento/$id'
      preLoaderRoute: typeof PeticionamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/resultados': {
      id: '/painel/resultados'
      path: '/painel/resultados'
      fullPath: '/painel/resultados'
      preLoaderRoute: typeof PainelResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/relatorios': {
      id: '/painel/relatorios'
      path: '/painel/relatorios'
      fullPath: '/painel/relatorios'
      preLoaderRoute: typeof PainelRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/demandas': {
      id: '/painel/demandas'
      path: '/painel/demandas'
      fullPath: '/painel/demandas'
      preLoaderRoute: typeof PainelDemandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/associados': {
      id: '/painel/associados'
      path: '/painel/associados'
      fullPath: '/painel/associados'
      preLoaderRoute: typeof PainelAssociadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/conteudos': {
      id: '/marketing/conteudos'
      path: '/marketing/conteudos'
      fullPath: '/marketing/conteudos'
      preLoaderRoute: typeof MarketingConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/calendario': {
      id: '/marketing/calendario'
      path: '/marketing/calendario'
      fullPath: '/marketing/calendario'
      preLoaderRoute: typeof MarketingCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/banco-midia': {
      id: '/marketing/banco-midia'
      path: '/marketing/banco-midia'
      fullPath: '/marketing/banco-midia'
      preLoaderRoute: typeof MarketingBancoMidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia/leads': {
      id: '/inteligencia/leads'
      path: '/inteligencia/leads'
      fullPath: '/inteligencia/leads'
      preLoaderRoute: typeof InteligenciaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/whatsapp': {
      id: '/dashboards/whatsapp'
      path: '/dashboards/whatsapp'
      fullPath: '/dashboards/whatsapp'
      preLoaderRoute: typeof DashboardsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/operacional': {
      id: '/dashboards/operacional'
      path: '/dashboards/operacional'
      fullPath: '/dashboards/operacional'
      preLoaderRoute: typeof DashboardsOperacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/marketing': {
      id: '/dashboards/marketing'
      path: '/dashboards/marketing'
      fullPath: '/dashboards/marketing'
      preLoaderRoute: typeof DashboardsMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/financeiro': {
      id: '/dashboards/financeiro'
      path: '/dashboards/financeiro'
      fullPath: '/dashboards/financeiro'
      preLoaderRoute: typeof DashboardsFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/comercial': {
      id: '/dashboards/comercial'
      path: '/dashboards/comercial'
      fullPath: '/dashboards/comercial'
      preLoaderRoute: typeof DashboardsComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/admin': {
      id: '/dashboards/admin'
      path: '/dashboards/admin'
      fullPath: '/dashboards/admin'
      preLoaderRoute: typeof DashboardsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/teses': {
      id: '/controladoria/teses'
      path: '/controladoria/teses'
      fullPath: '/controladoria/teses'
      preLoaderRoute: typeof ControladoriaTesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/prazos': {
      id: '/controladoria/prazos'
      path: '/controladoria/prazos'
      fullPath: '/controladoria/prazos'
      preLoaderRoute: typeof ControladoriaPrazosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/excecoes': {
      id: '/controladoria/excecoes'
      path: '/controladoria/excecoes'
      fullPath: '/controladoria/excecoes'
      preLoaderRoute: typeof ControladoriaExcecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/distribuicao': {
      id: '/controladoria/distribuicao'
      path: '/controladoria/distribuicao'
      fullPath: '/controladoria/distribuicao'
      preLoaderRoute: typeof ControladoriaDistribuicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/decisoes': {
      id: '/controladoria/decisoes'
      path: '/controladoria/decisoes'
      fullPath: '/controladoria/decisoes'
      preLoaderRoute: typeof ControladoriaDecisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/workflows': {
      id: '/configuracoes/workflows'
      path: '/workflows'
      fullPath: '/configuracoes/workflows'
      preLoaderRoute: typeof ConfiguracoesWorkflowsRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/tipos-tarefa': {
      id: '/configuracoes/tipos-tarefa'
      path: '/tipos-tarefa'
      fullPath: '/configuracoes/tipos-tarefa'
      preLoaderRoute: typeof ConfiguracoesTiposTarefaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/integracoes': {
      id: '/configuracoes/integracoes'
      path: '/integracoes'
      fullPath: '/configuracoes/integracoes'
      preLoaderRoute: typeof ConfiguracoesIntegracoesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/importacao': {
      id: '/configuracoes/importacao'
      path: '/importacao'
      fullPath: '/configuracoes/importacao'
      preLoaderRoute: typeof ConfiguracoesImportacaoRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/campos-personalizados': {
      id: '/configuracoes/campos-personalizados'
      path: '/campos-personalizados'
      fullPath: '/configuracoes/campos-personalizados'
      preLoaderRoute: typeof ConfiguracoesCamposPersonalizadosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/comercial/oportunidades': {
      id: '/comercial/oportunidades'
      path: '/comercial/oportunidades'
      fullPath: '/comercial/oportunidades'
      preLoaderRoute: typeof ComercialOportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/leads': {
      id: '/comercial/leads'
      path: '/comercial/leads'
      fullPath: '/comercial/leads'
      preLoaderRoute: typeof ComercialLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/funil': {
      id: '/comercial/funil'
      path: '/comercial/funil'
      fullPath: '/comercial/funil'
      preLoaderRoute: typeof ComercialFunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/email-marketing': {
      id: '/comercial/email-marketing'
      path: '/comercial/email-marketing'
      fullPath: '/comercial/email-marketing'
      preLoaderRoute: typeof ComercialEmailMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/assinaturas': {
      id: '/comercial/assinaturas'
      path: '/comercial/assinaturas'
      fullPath: '/comercial/assinaturas'
      preLoaderRoute: typeof ComercialAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/lista': {
      id: '/casos/lista'
      path: '/casos/lista'
      fullPath: '/casos/lista'
      preLoaderRoute: typeof CasosListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/financeiro': {
      id: '/casos/financeiro'
      path: '/casos/financeiro'
      fullPath: '/casos/financeiro'
      preLoaderRoute: typeof CasosFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/$id': {
      id: '/casos/$id'
      path: '/casos/$id'
      fullPath: '/casos/$id'
      preLoaderRoute: typeof CasosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/distribuicao/': {
      id: '/controladoria/distribuicao/'
      path: '/'
      fullPath: '/controladoria/distribuicao/'
      preLoaderRoute: typeof ControladoriaDistribuicaoIndexRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/casos/financeiro/': {
      id: '/casos/financeiro/'
      path: '/'
      fullPath: '/casos/financeiro/'
      preLoaderRoute: typeof CasosFinanceiroIndexRouteImport
      parentRoute: typeof CasosFinanceiroRoute
    }
    '/casos/$id/': {
      id: '/casos/$id/'
      path: '/'
      fullPath: '/casos/$id/'
      preLoaderRoute: typeof CasosIdIndexRouteImport
      parentRoute: typeof CasosIdRoute
    }
    '/whatsapp/conversas/$id': {
      id: '/whatsapp/conversas/$id'
      path: '/whatsapp/conversas/$id'
      fullPath: '/whatsapp/conversas/$id'
      preLoaderRoute: typeof WhatsappConversasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/casos/$id': {
      id: '/portal/casos/$id'
      path: '/portal/casos/$id'
      fullPath: '/portal/casos/$id'
      preLoaderRoute: typeof PortalCasosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/distribuicao/tipos-tarefa': {
      id: '/controladoria/distribuicao/tipos-tarefa'
      path: '/tipos-tarefa'
      fullPath: '/controladoria/distribuicao/tipos-tarefa'
      preLoaderRoute: typeof ControladoriaDistribuicaoTiposTarefaRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/temas': {
      id: '/controladoria/distribuicao/temas'
      path: '/temas'
      fullPath: '/controladoria/distribuicao/temas'
      preLoaderRoute: typeof ControladoriaDistribuicaoTemasRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/simulador': {
      id: '/controladoria/distribuicao/simulador'
      path: '/simulador'
      fullPath: '/controladoria/distribuicao/simulador'
      preLoaderRoute: typeof ControladoriaDistribuicaoSimuladorRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/relatorio': {
      id: '/controladoria/distribuicao/relatorio'
      path: '/relatorio'
      fullPath: '/controladoria/distribuicao/relatorio'
      preLoaderRoute: typeof ControladoriaDistribuicaoRelatorioRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/lista': {
      id: '/controladoria/distribuicao/lista'
      path: '/lista'
      fullPath: '/controladoria/distribuicao/lista'
      preLoaderRoute: typeof ControladoriaDistribuicaoListaRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/kanban': {
      id: '/controladoria/distribuicao/kanban'
      path: '/kanban'
      fullPath: '/controladoria/distribuicao/kanban'
      preLoaderRoute: typeof ControladoriaDistribuicaoKanbanRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/indicadores': {
      id: '/controladoria/distribuicao/indicadores'
      path: '/indicadores'
      fullPath: '/controladoria/distribuicao/indicadores'
      preLoaderRoute: typeof ControladoriaDistribuicaoIndicadoresRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/historico-tarefas': {
      id: '/controladoria/distribuicao/historico-tarefas'
      path: '/historico-tarefas'
      fullPath: '/controladoria/distribuicao/historico-tarefas'
      preLoaderRoute: typeof ControladoriaDistribuicaoHistoricoTarefasRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/historico-andamentos': {
      id: '/controladoria/distribuicao/historico-andamentos'
      path: '/historico-andamentos'
      fullPath: '/controladoria/distribuicao/historico-andamentos'
      preLoaderRoute: typeof ControladoriaDistribuicaoHistoricoAndamentosRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/historico': {
      id: '/controladoria/distribuicao/historico'
      path: '/historico'
      fullPath: '/controladoria/distribuicao/historico'
      preLoaderRoute: typeof ControladoriaDistribuicaoHistoricoRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/executores': {
      id: '/controladoria/distribuicao/executores'
      path: '/executores'
      fullPath: '/controladoria/distribuicao/executores'
      preLoaderRoute: typeof ControladoriaDistribuicaoExecutoresRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/excecoes': {
      id: '/controladoria/distribuicao/excecoes'
      path: '/excecoes'
      fullPath: '/controladoria/distribuicao/excecoes'
      preLoaderRoute: typeof ControladoriaDistribuicaoExcecoesRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/configuracao': {
      id: '/controladoria/distribuicao/configuracao'
      path: '/configuracao'
      fullPath: '/controladoria/distribuicao/configuracao'
      preLoaderRoute: typeof ControladoriaDistribuicaoConfiguracaoRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/calendario': {
      id: '/controladoria/distribuicao/calendario'
      path: '/calendario'
      fullPath: '/controladoria/distribuicao/calendario'
      preLoaderRoute: typeof ControladoriaDistribuicaoCalendarioRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/andamentos': {
      id: '/controladoria/distribuicao/andamentos'
      path: '/andamentos'
      fullPath: '/controladoria/distribuicao/andamentos'
      preLoaderRoute: typeof ControladoriaDistribuicaoAndamentosRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/controladoria/distribuicao/a-distribuir': {
      id: '/controladoria/distribuicao/a-distribuir'
      path: '/a-distribuir'
      fullPath: '/controladoria/distribuicao/a-distribuir'
      preLoaderRoute: typeof ControladoriaDistribuicaoADistribuirRouteImport
      parentRoute: typeof ControladoriaDistribuicaoRoute
    }
    '/casos/financeiro/inadimplencia': {
      id: '/casos/financeiro/inadimplencia'
      path: '/inadimplencia'
      fullPath: '/casos/financeiro/inadimplencia'
      preLoaderRoute: typeof CasosFinanceiroInadimplenciaRouteImport
      parentRoute: typeof CasosFinanceiroRoute
    }
    '/casos/financeiro/cobrancas': {
      id: '/casos/financeiro/cobrancas'
      path: '/cobrancas'
      fullPath: '/casos/financeiro/cobrancas'
      preLoaderRoute: typeof CasosFinanceiroCobrancasRouteImport
      parentRoute: typeof CasosFinanceiroRoute
    }
    '/casos/$id/termo': {
      id: '/casos/$id/termo'
      path: '/termo'
      fullPath: '/casos/$id/termo'
      preLoaderRoute: typeof CasosIdTermoRouteImport
      parentRoute: typeof CasosIdRoute
    }
    '/casos/$id/judicial': {
      id: '/casos/$id/judicial'
      path: '/judicial'
      fullPath: '/casos/$id/judicial'
      preLoaderRoute: typeof CasosIdJudicialRouteImport
      parentRoute: typeof CasosIdRoute
    }
    '/casos/$id/financeiro': {
      id: '/casos/$id/financeiro'
      path: '/financeiro'
      fullPath: '/casos/$id/financeiro'
      preLoaderRoute: typeof CasosIdFinanceiroRouteImport
      parentRoute: typeof CasosIdRoute
    }
    '/casos/$id/documentos': {
      id: '/casos/$id/documentos'
      path: '/documentos'
      fullPath: '/casos/$id/documentos'
      preLoaderRoute: typeof CasosIdDocumentosRouteImport
      parentRoute: typeof CasosIdRoute
    }
    '/api/webhooks/zapsign': {
      id: '/api/webhooks/zapsign'
      path: '/api/webhooks/zapsign'
      fullPath: '/api/webhooks/zapsign'
      preLoaderRoute: typeof ApiWebhooksZapsignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/n8n': {
      id: '/api/webhooks/n8n'
      path: '/api/webhooks/n8n'
      fullPath: '/api/webhooks/n8n'
      preLoaderRoute: typeof ApiWebhooksN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/asaas': {
      id: '/api/webhooks/asaas'
      path: '/api/webhooks/asaas'
      fullPath: '/api/webhooks/asaas'
      preLoaderRoute: typeof ApiWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-contaazul': {
      id: '/api/cron/sync-contaazul'
      path: '/api/cron/sync-contaazul'
      fullPath: '/api/cron/sync-contaazul'
      preLoaderRoute: typeof ApiCronSyncContaazulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-asaas': {
      id: '/api/cron/sync-asaas'
      path: '/api/cron/sync-asaas'
      fullPath: '/api/cron/sync-asaas'
      preLoaderRoute: typeof ApiCronSyncAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/distribuicao': {
      id: '/api/cron/distribuicao'
      path: '/api/cron/distribuicao'
      fullPath: '/api/cron/distribuicao'
      preLoaderRoute: typeof ApiCronDistribuicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily': {
      id: '/api/cron/daily'
      path: '/api/cron/daily'
      fullPath: '/api/cron/daily'
      preLoaderRoute: typeof ApiCronDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contaazul/callback': {
      id: '/api/contaazul/callback'
      path: '/api/contaazul/callback'
      fullPath: '/api/contaazul/callback'
      preLoaderRoute: typeof ApiContaazulCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/$id/termo/elaborar': {
      id: '/casos/$id/termo/elaborar'
      path: '/elaborar'
      fullPath: '/casos/$id/termo/elaborar'
      preLoaderRoute: typeof CasosIdTermoElaborarRouteImport
      parentRoute: typeof CasosIdTermoRoute
    }
    '/api/clients/$id/documents/': {
      id: '/api/clients/$id/documents/'
      path: '/api/clients/$id/documents'
      fullPath: '/api/clients/$id/documents/'
      preLoaderRoute: typeof ApiClientsIdDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/service-types/$id/templates/upload': {
      id: '/api/service-types/$id/templates/upload'
      path: '/api/service-types/$id/templates/upload'
      fullPath: '/api/service-types/$id/templates/upload'
      preLoaderRoute: typeof ApiServiceTypesIdTemplatesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id/documents/$docId': {
      id: '/api/clients/$id/documents/$docId'
      path: '/api/clients/$id/documents/$docId'
      fullPath: '/api/clients/$id/documents/$docId'
      preLoaderRoute: typeof ApiClientsIdDocumentsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cases/$id/documents/upload': {
      id: '/api/cases/$id/documents/upload'
      path: '/api/cases/$id/documents/upload'
      fullPath: '/api/cases/$id/documents/upload'
      preLoaderRoute: typeof ApiCasesIdDocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id/documents/$docId/download': {
      id: '/api/clients/$id/documents/$docId/download'
      path: '/download'
      fullPath: '/api/clients/$id/documents/$docId/download'
      preLoaderRoute: typeof ApiClientsIdDocumentsDocIdDownloadRouteImport
      parentRoute: typeof ApiClientsIdDocumentsDocIdRoute
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesCamposPersonalizadosRoute: typeof ConfiguracoesCamposPersonalizadosRoute
  ConfiguracoesImportacaoRoute: typeof ConfiguracoesImportacaoRoute
  ConfiguracoesIntegracoesRoute: typeof ConfiguracoesIntegracoesRoute
  ConfiguracoesTiposTarefaRoute: typeof ConfiguracoesTiposTarefaRoute
  ConfiguracoesWorkflowsRoute: typeof ConfiguracoesWorkflowsRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesCamposPersonalizadosRoute:
    ConfiguracoesCamposPersonalizadosRoute,
  ConfiguracoesImportacaoRoute: ConfiguracoesImportacaoRoute,
  ConfiguracoesIntegracoesRoute: ConfiguracoesIntegracoesRoute,
  ConfiguracoesTiposTarefaRoute: ConfiguracoesTiposTarefaRoute,
  ConfiguracoesWorkflowsRoute: ConfiguracoesWorkflowsRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface CasosIdTermoRouteChildren {
  CasosIdTermoElaborarRoute: typeof CasosIdTermoElaborarRoute
}

const CasosIdTermoRouteChildren: CasosIdTermoRouteChildren = {
  CasosIdTermoElaborarRoute: CasosIdTermoElaborarRoute,
}

const CasosIdTermoRouteWithChildren = CasosIdTermoRoute._addFileChildren(
  CasosIdTermoRouteChildren,
)

interface CasosIdRouteChildren {
  CasosIdDocumentosRoute: typeof CasosIdDocumentosRoute
  CasosIdFinanceiroRoute: typeof CasosIdFinanceiroRoute
  CasosIdJudicialRoute: typeof CasosIdJudicialRoute
  CasosIdTermoRoute: typeof CasosIdTermoRouteWithChildren
  CasosIdIndexRoute: typeof CasosIdIndexRoute
}

const CasosIdRouteChildren: CasosIdRouteChildren = {
  CasosIdDocumentosRoute: CasosIdDocumentosRoute,
  CasosIdFinanceiroRoute: CasosIdFinanceiroRoute,
  CasosIdJudicialRoute: CasosIdJudicialRoute,
  CasosIdTermoRoute: CasosIdTermoRouteWithChildren,
  CasosIdIndexRoute: CasosIdIndexRoute,
}

const CasosIdRouteWithChildren =
  CasosIdRoute._addFileChildren(CasosIdRouteChildren)

interface CasosFinanceiroRouteChildren {
  CasosFinanceiroCobrancasRoute: typeof CasosFinanceiroCobrancasRoute
  CasosFinanceiroInadimplenciaRoute: typeof CasosFinanceiroInadimplenciaRoute
  CasosFinanceiroIndexRoute: typeof CasosFinanceiroIndexRoute
}

const CasosFinanceiroRouteChildren: CasosFinanceiroRouteChildren = {
  CasosFinanceiroCobrancasRoute: CasosFinanceiroCobrancasRoute,
  CasosFinanceiroInadimplenciaRoute: CasosFinanceiroInadimplenciaRoute,
  CasosFinanceiroIndexRoute: CasosFinanceiroIndexRoute,
}

const CasosFinanceiroRouteWithChildren = CasosFinanceiroRoute._addFileChildren(
  CasosFinanceiroRouteChildren,
)

interface ControladoriaDistribuicaoRouteChildren {
  ControladoriaDistribuicaoADistribuirRoute: typeof ControladoriaDistribuicaoADistribuirRoute
  ControladoriaDistribuicaoAndamentosRoute: typeof ControladoriaDistribuicaoAndamentosRoute
  ControladoriaDistribuicaoCalendarioRoute: typeof ControladoriaDistribuicaoCalendarioRoute
  ControladoriaDistribuicaoConfiguracaoRoute: typeof ControladoriaDistribuicaoConfiguracaoRoute
  ControladoriaDistribuicaoExcecoesRoute: typeof ControladoriaDistribuicaoExcecoesRoute
  ControladoriaDistribuicaoExecutoresRoute: typeof ControladoriaDistribuicaoExecutoresRoute
  ControladoriaDistribuicaoHistoricoRoute: typeof ControladoriaDistribuicaoHistoricoRoute
  ControladoriaDistribuicaoHistoricoAndamentosRoute: typeof ControladoriaDistribuicaoHistoricoAndamentosRoute
  ControladoriaDistribuicaoHistoricoTarefasRoute: typeof ControladoriaDistribuicaoHistoricoTarefasRoute
  ControladoriaDistribuicaoIndicadoresRoute: typeof ControladoriaDistribuicaoIndicadoresRoute
  ControladoriaDistribuicaoKanbanRoute: typeof ControladoriaDistribuicaoKanbanRoute
  ControladoriaDistribuicaoListaRoute: typeof ControladoriaDistribuicaoListaRoute
  ControladoriaDistribuicaoRelatorioRoute: typeof ControladoriaDistribuicaoRelatorioRoute
  ControladoriaDistribuicaoSimuladorRoute: typeof ControladoriaDistribuicaoSimuladorRoute
  ControladoriaDistribuicaoTemasRoute: typeof ControladoriaDistribuicaoTemasRoute
  ControladoriaDistribuicaoTiposTarefaRoute: typeof ControladoriaDistribuicaoTiposTarefaRoute
  ControladoriaDistribuicaoIndexRoute: typeof ControladoriaDistribuicaoIndexRoute
}

const ControladoriaDistribuicaoRouteChildren: ControladoriaDistribuicaoRouteChildren =
  {
    ControladoriaDistribuicaoADistribuirRoute:
      ControladoriaDistribuicaoADistribuirRoute,
    ControladoriaDistribuicaoAndamentosRoute:
      ControladoriaDistribuicaoAndamentosRoute,
    ControladoriaDistribuicaoCalendarioRoute:
      ControladoriaDistribuicaoCalendarioRoute,
    ControladoriaDistribuicaoConfiguracaoRoute:
      ControladoriaDistribuicaoConfiguracaoRoute,
    ControladoriaDistribuicaoExcecoesRoute:
      ControladoriaDistribuicaoExcecoesRoute,
    ControladoriaDistribuicaoExecutoresRoute:
      ControladoriaDistribuicaoExecutoresRoute,
    ControladoriaDistribuicaoHistoricoRoute:
      ControladoriaDistribuicaoHistoricoRoute,
    ControladoriaDistribuicaoHistoricoAndamentosRoute:
      ControladoriaDistribuicaoHistoricoAndamentosRoute,
    ControladoriaDistribuicaoHistoricoTarefasRoute:
      ControladoriaDistribuicaoHistoricoTarefasRoute,
    ControladoriaDistribuicaoIndicadoresRoute:
      ControladoriaDistribuicaoIndicadoresRoute,
    ControladoriaDistribuicaoKanbanRoute: ControladoriaDistribuicaoKanbanRoute,
    ControladoriaDistribuicaoListaRoute: ControladoriaDistribuicaoListaRoute,
    ControladoriaDistribuicaoRelatorioRoute:
      ControladoriaDistribuicaoRelatorioRoute,
    ControladoriaDistribuicaoSimuladorRoute:
      ControladoriaDistribuicaoSimuladorRoute,
    ControladoriaDistribuicaoTemasRoute: ControladoriaDistribuicaoTemasRoute,
    ControladoriaDistribuicaoTiposTarefaRoute:
      ControladoriaDistribuicaoTiposTarefaRoute,
    ControladoriaDistribuicaoIndexRoute: ControladoriaDistribuicaoIndexRoute,
  }

const ControladoriaDistribuicaoRouteWithChildren =
  ControladoriaDistribuicaoRoute._addFileChildren(
    ControladoriaDistribuicaoRouteChildren,
  )

interface ApiClientsIdDocumentsDocIdRouteChildren {
  ApiClientsIdDocumentsDocIdDownloadRoute: typeof ApiClientsIdDocumentsDocIdDownloadRoute
}

const ApiClientsIdDocumentsDocIdRouteChildren: ApiClientsIdDocumentsDocIdRouteChildren =
  {
    ApiClientsIdDocumentsDocIdDownloadRoute:
      ApiClientsIdDocumentsDocIdDownloadRoute,
  }

const ApiClientsIdDocumentsDocIdRouteWithChildren =
  ApiClientsIdDocumentsDocIdRoute._addFileChildren(
    ApiClientsIdDocumentsDocIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  DefinirSenhaRoute: DefinirSenhaRoute,
  DesignSystemRoute: DesignSystemRoute,
  EntrarRoute: EntrarRoute,
  HojeRoute: HojeRoute,
  LoginRoute: LoginRoute,
  ModelosRoute: ModelosRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  PermissoesRoute: PermissoesRoute,
  PipelineRoute: PipelineRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ReferenciasRoute: ReferenciasRoute,
  RelatorioFinanceiroRoute: RelatorioFinanceiroRoute,
  TarefasRoute: TarefasRoute,
  CasosIdRoute: CasosIdRouteWithChildren,
  CasosFinanceiroRoute: CasosFinanceiroRouteWithChildren,
  CasosListaRoute: CasosListaRoute,
  ClientesIdRoute: ClientesIdRoute,
  ComercialAssinaturasRoute: ComercialAssinaturasRoute,
  ComercialEmailMarketingRoute: ComercialEmailMarketingRoute,
  ComercialFunilRoute: ComercialFunilRoute,
  ComercialLeadsRoute: ComercialLeadsRoute,
  ComercialOportunidadesRoute: ComercialOportunidadesRoute,
  ControladoriaDecisoesRoute: ControladoriaDecisoesRoute,
  ControladoriaDistribuicaoRoute: ControladoriaDistribuicaoRouteWithChildren,
  ControladoriaExcecoesRoute: ControladoriaExcecoesRoute,
  ControladoriaPrazosRoute: ControladoriaPrazosRoute,
  ControladoriaTesesRoute: ControladoriaTesesRoute,
  DashboardsAdminRoute: DashboardsAdminRoute,
  DashboardsComercialRoute: DashboardsComercialRoute,
  DashboardsFinanceiroRoute: DashboardsFinanceiroRoute,
  DashboardsMarketingRoute: DashboardsMarketingRoute,
  DashboardsOperacionalRoute: DashboardsOperacionalRoute,
  DashboardsWhatsappRoute: DashboardsWhatsappRoute,
  InteligenciaLeadsRoute: InteligenciaLeadsRoute,
  MarketingBancoMidiaRoute: MarketingBancoMidiaRoute,
  MarketingCalendarioRoute: MarketingCalendarioRoute,
  MarketingConteudosRoute: MarketingConteudosRoute,
  PainelAssociadosRoute: PainelAssociadosRoute,
  PainelDemandasRoute: PainelDemandasRoute,
  PainelRelatoriosRoute: PainelRelatoriosRoute,
  PainelResultadosRoute: PainelResultadosRoute,
  PeticionamentoIdRoute: PeticionamentoIdRoute,
  PeticionamentoBancoPecasRoute: PeticionamentoBancoPecasRoute,
  PortalBoletosRoute: PortalBoletosRoute,
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalMensagensRoute: PortalMensagensRoute,
  PortalPerfilRoute: PortalPerfilRoute,
  WhatsappAgenteRoute: WhatsappAgenteRoute,
  CasosIndexRoute: CasosIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ComercialIndexRoute: ComercialIndexRoute,
  ControladoriaIndexRoute: ControladoriaIndexRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
  PeticionamentoIndexRoute: PeticionamentoIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  WhatsappIndexRoute: WhatsappIndexRoute,
  ApiContaazulCallbackRoute: ApiContaazulCallbackRoute,
  ApiCronDailyRoute: ApiCronDailyRoute,
  ApiCronDistribuicaoRoute: ApiCronDistribuicaoRoute,
  ApiCronSyncAsaasRoute: ApiCronSyncAsaasRoute,
  ApiCronSyncContaazulRoute: ApiCronSyncContaazulRoute,
  ApiWebhooksAsaasRoute: ApiWebhooksAsaasRoute,
  ApiWebhooksN8nRoute: ApiWebhooksN8nRoute,
  ApiWebhooksZapsignRoute: ApiWebhooksZapsignRoute,
  PortalCasosIdRoute: PortalCasosIdRoute,
  WhatsappConversasIdRoute: WhatsappConversasIdRoute,
  ApiCasesIdDocumentsUploadRoute: ApiCasesIdDocumentsUploadRoute,
  ApiClientsIdDocumentsDocIdRoute: ApiClientsIdDocumentsDocIdRouteWithChildren,
  ApiServiceTypesIdTemplatesUploadRoute: ApiServiceTypesIdTemplatesUploadRoute,
  ApiClientsIdDocumentsIndexRoute: ApiClientsIdDocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
