/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappIndexRouteImport } from './routes/whatsapp.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PeticionamentoIndexRouteImport } from './routes/peticionamento.index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards.index'
import { Route as ControladoriaIndexRouteImport } from './routes/controladoria.index'
import { Route as ComercialIndexRouteImport } from './routes/comercial.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as CasosIndexRouteImport } from './routes/casos.index'
import { Route as WhatsappAgenteRouteImport } from './routes/whatsapp.agente'
import { Route as PortalPerfilRouteImport } from './routes/portal.perfil'
import { Route as PortalMensagensRouteImport } from './routes/portal.mensagens'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as PortalBoletosRouteImport } from './routes/portal.boletos'
import { Route as PeticionamentoBancoPecasRouteImport } from './routes/peticionamento.banco-pecas'
import { Route as PeticionamentoIdRouteImport } from './routes/peticionamento.$id'
import { Route as PainelResultadosRouteImport } from './routes/painel.resultados'
import { Route as PainelRelatoriosRouteImport } from './routes/painel.relatorios'
import { Route as PainelDemandasRouteImport } from './routes/painel.demandas'
import { Route as PainelAssociadosRouteImport } from './routes/painel.associados'
import { Route as MarketingConteudosRouteImport } from './routes/marketing.conteudos'
import { Route as MarketingCalendarioRouteImport } from './routes/marketing.calendario'
import { Route as MarketingBancoMidiaRouteImport } from './routes/marketing.banco-midia'
import { Route as DashboardsWhatsappRouteImport } from './routes/dashboards.whatsapp'
import { Route as DashboardsOperacionalRouteImport } from './routes/dashboards.operacional'
import { Route as DashboardsMarketingRouteImport } from './routes/dashboards.marketing'
import { Route as DashboardsFinanceiroRouteImport } from './routes/dashboards.financeiro'
import { Route as DashboardsComercialRouteImport } from './routes/dashboards.comercial'
import { Route as DashboardsAdminRouteImport } from './routes/dashboards.admin'
import { Route as ControladoriaTesesRouteImport } from './routes/controladoria.teses'
import { Route as ControladoriaPrazosRouteImport } from './routes/controladoria.prazos'
import { Route as ControladoriaExcecoesRouteImport } from './routes/controladoria.excecoes'
import { Route as ControladoriaDecisoesRouteImport } from './routes/controladoria.decisoes'
import { Route as ComercialOportunidadesRouteImport } from './routes/comercial.oportunidades'
import { Route as ComercialLeadsRouteImport } from './routes/comercial.leads'
import { Route as ComercialFunilRouteImport } from './routes/comercial.funil'
import { Route as ComercialEmailMarketingRouteImport } from './routes/comercial.email-marketing'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as CasosListaRouteImport } from './routes/casos.lista'
import { Route as CasosFinanceiroRouteImport } from './routes/casos.financeiro'
import { Route as CasosIdRouteImport } from './routes/casos.$id'
import { Route as CasosFinanceiroIndexRouteImport } from './routes/casos.financeiro.index'
import { Route as WhatsappConversasIdRouteImport } from './routes/whatsapp.conversas.$id'
import { Route as PortalCasosIdRouteImport } from './routes/portal.casos.$id'
import { Route as CasosFinanceiroInadimplenciaRouteImport } from './routes/casos.financeiro.inadimplencia'
import { Route as CasosIdTermoRouteImport } from './routes/casos.$id.termo'
import { Route as ApiWebhooksZapsignRouteImport } from './routes/api.webhooks.zapsign'
import { Route as CasosIdTermoElaborarRouteImport } from './routes/casos.$id.termo.elaborar'
import { Route as ApiClientsIdDocumentsIndexRouteImport } from './routes/api.clients.$id.documents.index'
import { Route as ApiClientsIdDocumentsDocIdRouteImport } from './routes/api.clients.$id.documents.$docId'
import { Route as ApiClientsIdDocumentsDocIdDownloadRouteImport } from './routes/api.clients.$id.documents.$docId.download'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappIndexRoute = WhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeticionamentoIndexRoute = PeticionamentoIndexRouteImport.update({
  id: '/peticionamento/',
  path: '/peticionamento/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaIndexRoute = ControladoriaIndexRouteImport.update({
  id: '/controladoria/',
  path: '/controladoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialIndexRoute = ComercialIndexRouteImport.update({
  id: '/comercial/',
  path: '/comercial/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIndexRoute = CasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappAgenteRoute = WhatsappAgenteRouteImport.update({
  id: '/whatsapp/agente',
  path: '/whatsapp/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPerfilRoute = PortalPerfilRouteImport.update({
  id: '/portal/perfil',
  path: '/portal/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMensagensRoute = PortalMensagensRouteImport.update({
  id: '/portal/mensagens',
  path: '/portal/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/portal/documentos',
  path: '/portal/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBoletosRoute = PortalBoletosRouteImport.update({
  id: '/portal/boletos',
  path: '/portal/boletos',
  getParentRoute: () => rootRouteImport,
} as any)
const PeticionamentoBancoPecasRoute =
  PeticionamentoBancoPecasRouteImport.update({
    id: '/peticionamento/banco-pecas',
    path: '/peticionamento/banco-pecas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PeticionamentoIdRoute = PeticionamentoIdRouteImport.update({
  id: '/peticionamento/$id',
  path: '/peticionamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelResultadosRoute = PainelResultadosRouteImport.update({
  id: '/painel/resultados',
  path: '/painel/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRelatoriosRoute = PainelRelatoriosRouteImport.update({
  id: '/painel/relatorios',
  path: '/painel/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelDemandasRoute = PainelDemandasRouteImport.update({
  id: '/painel/demandas',
  path: '/painel/demandas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAssociadosRoute = PainelAssociadosRouteImport.update({
  id: '/painel/associados',
  path: '/painel/associados',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingConteudosRoute = MarketingConteudosRouteImport.update({
  id: '/marketing/conteudos',
  path: '/marketing/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCalendarioRoute = MarketingCalendarioRouteImport.update({
  id: '/marketing/calendario',
  path: '/marketing/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingBancoMidiaRoute = MarketingBancoMidiaRouteImport.update({
  id: '/marketing/banco-midia',
  path: '/marketing/banco-midia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsWhatsappRoute = DashboardsWhatsappRouteImport.update({
  id: '/dashboards/whatsapp',
  path: '/dashboards/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsOperacionalRoute = DashboardsOperacionalRouteImport.update({
  id: '/dashboards/operacional',
  path: '/dashboards/operacional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsMarketingRoute = DashboardsMarketingRouteImport.update({
  id: '/dashboards/marketing',
  path: '/dashboards/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsFinanceiroRoute = DashboardsFinanceiroRouteImport.update({
  id: '/dashboards/financeiro',
  path: '/dashboards/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsComercialRoute = DashboardsComercialRouteImport.update({
  id: '/dashboards/comercial',
  path: '/dashboards/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsAdminRoute = DashboardsAdminRouteImport.update({
  id: '/dashboards/admin',
  path: '/dashboards/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaTesesRoute = ControladoriaTesesRouteImport.update({
  id: '/controladoria/teses',
  path: '/controladoria/teses',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaPrazosRoute = ControladoriaPrazosRouteImport.update({
  id: '/controladoria/prazos',
  path: '/controladoria/prazos',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaExcecoesRoute = ControladoriaExcecoesRouteImport.update({
  id: '/controladoria/excecoes',
  path: '/controladoria/excecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaDecisoesRoute = ControladoriaDecisoesRouteImport.update({
  id: '/controladoria/decisoes',
  path: '/controladoria/decisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialOportunidadesRoute = ComercialOportunidadesRouteImport.update({
  id: '/comercial/oportunidades',
  path: '/comercial/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialLeadsRoute = ComercialLeadsRouteImport.update({
  id: '/comercial/leads',
  path: '/comercial/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialFunilRoute = ComercialFunilRouteImport.update({
  id: '/comercial/funil',
  path: '/comercial/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialEmailMarketingRoute = ComercialEmailMarketingRouteImport.update({
  id: '/comercial/email-marketing',
  path: '/comercial/email-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosListaRoute = CasosListaRouteImport.update({
  id: '/casos/lista',
  path: '/casos/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosFinanceiroRoute = CasosFinanceiroRouteImport.update({
  id: '/casos/financeiro',
  path: '/casos/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIdRoute = CasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosFinanceiroIndexRoute = CasosFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasosFinanceiroRoute,
} as any)
const WhatsappConversasIdRoute = WhatsappConversasIdRouteImport.update({
  id: '/whatsapp/conversas/$id',
  path: '/whatsapp/conversas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCasosIdRoute = PortalCasosIdRouteImport.update({
  id: '/portal/casos/$id',
  path: '/portal/casos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosFinanceiroInadimplenciaRoute =
  CasosFinanceiroInadimplenciaRouteImport.update({
    id: '/inadimplencia',
    path: '/inadimplencia',
    getParentRoute: () => CasosFinanceiroRoute,
  } as any)
const CasosIdTermoRoute = CasosIdTermoRouteImport.update({
  id: '/termo',
  path: '/termo',
  getParentRoute: () => CasosIdRoute,
} as any)
const ApiWebhooksZapsignRoute = ApiWebhooksZapsignRouteImport.update({
  id: '/api/webhooks/zapsign',
  path: '/api/webhooks/zapsign',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIdTermoElaborarRoute = CasosIdTermoElaborarRouteImport.update({
  id: '/elaborar',
  path: '/elaborar',
  getParentRoute: () => CasosIdTermoRoute,
} as any)
const ApiClientsIdDocumentsIndexRoute =
  ApiClientsIdDocumentsIndexRouteImport.update({
    id: '/api/clients/$id/documents/',
    path: '/api/clients/$id/documents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiClientsIdDocumentsDocIdRoute =
  ApiClientsIdDocumentsDocIdRouteImport.update({
    id: '/api/clients/$id/documents/$docId',
    path: '/api/clients/$id/documents/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiClientsIdDocumentsDocIdDownloadRoute =
  ApiClientsIdDocumentsDocIdDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiClientsIdDocumentsDocIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/tarefas': typeof TarefasRoute
  '/casos/$id': typeof CasosIdRouteWithChildren
  '/casos/financeiro': typeof CasosFinanceiroRouteWithChildren
  '/casos/lista': typeof CasosListaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/email-marketing': typeof ComercialEmailMarketingRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/comercial/oportunidades': typeof ComercialOportunidadesRoute
  '/controladoria/decisoes': typeof ControladoriaDecisoesRoute
  '/controladoria/excecoes': typeof ControladoriaExcecoesRoute
  '/controladoria/prazos': typeof ControladoriaPrazosRoute
  '/controladoria/teses': typeof ControladoriaTesesRoute
  '/dashboards/admin': typeof DashboardsAdminRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/marketing': typeof DashboardsMarketingRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/dashboards/whatsapp': typeof DashboardsWhatsappRoute
  '/marketing/banco-midia': typeof MarketingBancoMidiaRoute
  '/marketing/calendario': typeof MarketingCalendarioRoute
  '/marketing/conteudos': typeof MarketingConteudosRoute
  '/painel/associados': typeof PainelAssociadosRoute
  '/painel/demandas': typeof PainelDemandasRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/resultados': typeof PainelResultadosRoute
  '/peticionamento/$id': typeof PeticionamentoIdRoute
  '/peticionamento/banco-pecas': typeof PeticionamentoBancoPecasRoute
  '/portal/boletos': typeof PortalBoletosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/whatsapp/agente': typeof WhatsappAgenteRoute
  '/casos/': typeof CasosIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/controladoria/': typeof ControladoriaIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/peticionamento/': typeof PeticionamentoIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/whatsapp/': typeof WhatsappIndexRoute
  '/api/webhooks/zapsign': typeof ApiWebhooksZapsignRoute
  '/casos/$id/termo': typeof CasosIdTermoRouteWithChildren
  '/casos/financeiro/inadimplencia': typeof CasosFinanceiroInadimplenciaRoute
  '/portal/casos/$id': typeof PortalCasosIdRoute
  '/whatsapp/conversas/$id': typeof WhatsappConversasIdRoute
  '/casos/financeiro/': typeof CasosFinanceiroIndexRoute
  '/casos/$id/termo/elaborar': typeof CasosIdTermoElaborarRoute
  '/api/clients/$id/documents/$docId': typeof ApiClientsIdDocumentsDocIdRouteWithChildren
  '/api/clients/$id/documents/': typeof ApiClientsIdDocumentsIndexRoute
  '/api/clients/$id/documents/$docId/download': typeof ApiClientsIdDocumentsDocIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/tarefas': typeof TarefasRoute
  '/casos/$id': typeof CasosIdRouteWithChildren
  '/casos/lista': typeof CasosListaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/email-marketing': typeof ComercialEmailMarketingRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/comercial/oportunidades': typeof ComercialOportunidadesRoute
  '/controladoria/decisoes': typeof ControladoriaDecisoesRoute
  '/controladoria/excecoes': typeof ControladoriaExcecoesRoute
  '/controladoria/prazos': typeof ControladoriaPrazosRoute
  '/controladoria/teses': typeof ControladoriaTesesRoute
  '/dashboards/admin': typeof DashboardsAdminRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/marketing': typeof DashboardsMarketingRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/dashboards/whatsapp': typeof DashboardsWhatsappRoute
  '/marketing/banco-midia': typeof MarketingBancoMidiaRoute
  '/marketing/calendario': typeof MarketingCalendarioRoute
  '/marketing/conteudos': typeof MarketingConteudosRoute
  '/painel/associados': typeof PainelAssociadosRoute
  '/painel/demandas': typeof PainelDemandasRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/resultados': typeof PainelResultadosRoute
  '/peticionamento/$id': typeof PeticionamentoIdRoute
  '/peticionamento/banco-pecas': typeof PeticionamentoBancoPecasRoute
  '/portal/boletos': typeof PortalBoletosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/whatsapp/agente': typeof WhatsappAgenteRoute
  '/casos': typeof CasosIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/comercial': typeof ComercialIndexRoute
  '/controladoria': typeof ControladoriaIndexRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/painel': typeof PainelIndexRoute
  '/peticionamento': typeof PeticionamentoIndexRoute
  '/portal': typeof PortalIndexRoute
  '/whatsapp': typeof WhatsappIndexRoute
  '/api/webhooks/zapsign': typeof ApiWebhooksZapsignRoute
  '/casos/$id/termo': typeof CasosIdTermoRouteWithChildren
  '/casos/financeiro/inadimplencia': typeof CasosFinanceiroInadimplenciaRoute
  '/portal/casos/$id': typeof PortalCasosIdRoute
  '/whatsapp/conversas/$id': typeof WhatsappConversasIdRoute
  '/casos/financeiro': typeof CasosFinanceiroIndexRoute
  '/casos/$id/termo/elaborar': typeof CasosIdTermoElaborarRoute
  '/api/clients/$id/documents/$docId': typeof ApiClientsIdDocumentsDocIdRouteWithChildren
  '/api/clients/$id/documents': typeof ApiClientsIdDocumentsIndexRoute
  '/api/clients/$id/documents/$docId/download': typeof ApiClientsIdDocumentsDocIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/design-system': typeof DesignSystemRoute
  '/entrar': typeof EntrarRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/tarefas': typeof TarefasRoute
  '/casos/$id': typeof CasosIdRouteWithChildren
  '/casos/financeiro': typeof CasosFinanceiroRouteWithChildren
  '/casos/lista': typeof CasosListaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/email-marketing': typeof ComercialEmailMarketingRoute
  '/comercial/funil': typeof ComercialFunilRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/comercial/oportunidades': typeof ComercialOportunidadesRoute
  '/controladoria/decisoes': typeof ControladoriaDecisoesRoute
  '/controladoria/excecoes': typeof ControladoriaExcecoesRoute
  '/controladoria/prazos': typeof ControladoriaPrazosRoute
  '/controladoria/teses': typeof ControladoriaTesesRoute
  '/dashboards/admin': typeof DashboardsAdminRoute
  '/dashboards/comercial': typeof DashboardsComercialRoute
  '/dashboards/financeiro': typeof DashboardsFinanceiroRoute
  '/dashboards/marketing': typeof DashboardsMarketingRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/dashboards/whatsapp': typeof DashboardsWhatsappRoute
  '/marketing/banco-midia': typeof MarketingBancoMidiaRoute
  '/marketing/calendario': typeof MarketingCalendarioRoute
  '/marketing/conteudos': typeof MarketingConteudosRoute
  '/painel/associados': typeof PainelAssociadosRoute
  '/painel/demandas': typeof PainelDemandasRoute
  '/painel/relatorios': typeof PainelRelatoriosRoute
  '/painel/resultados': typeof PainelResultadosRoute
  '/peticionamento/$id': typeof PeticionamentoIdRoute
  '/peticionamento/banco-pecas': typeof PeticionamentoBancoPecasRoute
  '/portal/boletos': typeof PortalBoletosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/mensagens': typeof PortalMensagensRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/whatsapp/agente': typeof WhatsappAgenteRoute
  '/casos/': typeof CasosIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/controladoria/': typeof ControladoriaIndexRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/peticionamento/': typeof PeticionamentoIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/whatsapp/': typeof WhatsappIndexRoute
  '/api/webhooks/zapsign': typeof ApiWebhooksZapsignRoute
  '/casos/$id/termo': typeof CasosIdTermoRouteWithChildren
  '/casos/financeiro/inadimplencia': typeof CasosFinanceiroInadimplenciaRoute
  '/portal/casos/$id': typeof PortalCasosIdRoute
  '/whatsapp/conversas/$id': typeof WhatsappConversasIdRoute
  '/casos/financeiro/': typeof CasosFinanceiroIndexRoute
  '/casos/$id/termo/elaborar': typeof CasosIdTermoElaborarRoute
  '/api/clients/$id/documents/$docId': typeof ApiClientsIdDocumentsDocIdRouteWithChildren
  '/api/clients/$id/documents/': typeof ApiClientsIdDocumentsIndexRoute
  '/api/clients/$id/documents/$docId/download': typeof ApiClientsIdDocumentsDocIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/design-system'
    | '/entrar'
    | '/hoje'
    | '/login'
    | '/tarefas'
    | '/casos/$id'
    | '/casos/financeiro'
    | '/casos/lista'
    | '/clientes/$id'
    | '/comercial/email-marketing'
    | '/comercial/funil'
    | '/comercial/leads'
    | '/comercial/oportunidades'
    | '/controladoria/decisoes'
    | '/controladoria/excecoes'
    | '/controladoria/prazos'
    | '/controladoria/teses'
    | '/dashboards/admin'
    | '/dashboards/comercial'
    | '/dashboards/financeiro'
    | '/dashboards/marketing'
    | '/dashboards/operacional'
    | '/dashboards/whatsapp'
    | '/marketing/banco-midia'
    | '/marketing/calendario'
    | '/marketing/conteudos'
    | '/painel/associados'
    | '/painel/demandas'
    | '/painel/relatorios'
    | '/painel/resultados'
    | '/peticionamento/$id'
    | '/peticionamento/banco-pecas'
    | '/portal/boletos'
    | '/portal/documentos'
    | '/portal/mensagens'
    | '/portal/perfil'
    | '/whatsapp/agente'
    | '/casos/'
    | '/clientes/'
    | '/comercial/'
    | '/controladoria/'
    | '/dashboards/'
    | '/marketing/'
    | '/painel/'
    | '/peticionamento/'
    | '/portal/'
    | '/whatsapp/'
    | '/api/webhooks/zapsign'
    | '/casos/$id/termo'
    | '/casos/financeiro/inadimplencia'
    | '/portal/casos/$id'
    | '/whatsapp/conversas/$id'
    | '/casos/financeiro/'
    | '/casos/$id/termo/elaborar'
    | '/api/clients/$id/documents/$docId'
    | '/api/clients/$id/documents/'
    | '/api/clients/$id/documents/$docId/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/design-system'
    | '/entrar'
    | '/hoje'
    | '/login'
    | '/tarefas'
    | '/casos/$id'
    | '/casos/lista'
    | '/clientes/$id'
    | '/comercial/email-marketing'
    | '/comercial/funil'
    | '/comercial/leads'
    | '/comercial/oportunidades'
    | '/controladoria/decisoes'
    | '/controladoria/excecoes'
    | '/controladoria/prazos'
    | '/controladoria/teses'
    | '/dashboards/admin'
    | '/dashboards/comercial'
    | '/dashboards/financeiro'
    | '/dashboards/marketing'
    | '/dashboards/operacional'
    | '/dashboards/whatsapp'
    | '/marketing/banco-midia'
    | '/marketing/calendario'
    | '/marketing/conteudos'
    | '/painel/associados'
    | '/painel/demandas'
    | '/painel/relatorios'
    | '/painel/resultados'
    | '/peticionamento/$id'
    | '/peticionamento/banco-pecas'
    | '/portal/boletos'
    | '/portal/documentos'
    | '/portal/mensagens'
    | '/portal/perfil'
    | '/whatsapp/agente'
    | '/casos'
    | '/clientes'
    | '/comercial'
    | '/controladoria'
    | '/dashboards'
    | '/marketing'
    | '/painel'
    | '/peticionamento'
    | '/portal'
    | '/whatsapp'
    | '/api/webhooks/zapsign'
    | '/casos/$id/termo'
    | '/casos/financeiro/inadimplencia'
    | '/portal/casos/$id'
    | '/whatsapp/conversas/$id'
    | '/casos/financeiro'
    | '/casos/$id/termo/elaborar'
    | '/api/clients/$id/documents/$docId'
    | '/api/clients/$id/documents'
    | '/api/clients/$id/documents/$docId/download'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/design-system'
    | '/entrar'
    | '/hoje'
    | '/login'
    | '/tarefas'
    | '/casos/$id'
    | '/casos/financeiro'
    | '/casos/lista'
    | '/clientes/$id'
    | '/comercial/email-marketing'
    | '/comercial/funil'
    | '/comercial/leads'
    | '/comercial/oportunidades'
    | '/controladoria/decisoes'
    | '/controladoria/excecoes'
    | '/controladoria/prazos'
    | '/controladoria/teses'
    | '/dashboards/admin'
    | '/dashboards/comercial'
    | '/dashboards/financeiro'
    | '/dashboards/marketing'
    | '/dashboards/operacional'
    | '/dashboards/whatsapp'
    | '/marketing/banco-midia'
    | '/marketing/calendario'
    | '/marketing/conteudos'
    | '/painel/associados'
    | '/painel/demandas'
    | '/painel/relatorios'
    | '/painel/resultados'
    | '/peticionamento/$id'
    | '/peticionamento/banco-pecas'
    | '/portal/boletos'
    | '/portal/documentos'
    | '/portal/mensagens'
    | '/portal/perfil'
    | '/whatsapp/agente'
    | '/casos/'
    | '/clientes/'
    | '/comercial/'
    | '/controladoria/'
    | '/dashboards/'
    | '/marketing/'
    | '/painel/'
    | '/peticionamento/'
    | '/portal/'
    | '/whatsapp/'
    | '/api/webhooks/zapsign'
    | '/casos/$id/termo'
    | '/casos/financeiro/inadimplencia'
    | '/portal/casos/$id'
    | '/whatsapp/conversas/$id'
    | '/casos/financeiro/'
    | '/casos/$id/termo/elaborar'
    | '/api/clients/$id/documents/$docId'
    | '/api/clients/$id/documents/'
    | '/api/clients/$id/documents/$docId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EntrarRoute: typeof EntrarRoute
  HojeRoute: typeof HojeRoute
  LoginRoute: typeof LoginRoute
  TarefasRoute: typeof TarefasRoute
  CasosIdRoute: typeof CasosIdRouteWithChildren
  CasosFinanceiroRoute: typeof CasosFinanceiroRouteWithChildren
  CasosListaRoute: typeof CasosListaRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ComercialEmailMarketingRoute: typeof ComercialEmailMarketingRoute
  ComercialFunilRoute: typeof ComercialFunilRoute
  ComercialLeadsRoute: typeof ComercialLeadsRoute
  ComercialOportunidadesRoute: typeof ComercialOportunidadesRoute
  ControladoriaDecisoesRoute: typeof ControladoriaDecisoesRoute
  ControladoriaExcecoesRoute: typeof ControladoriaExcecoesRoute
  ControladoriaPrazosRoute: typeof ControladoriaPrazosRoute
  ControladoriaTesesRoute: typeof ControladoriaTesesRoute
  DashboardsAdminRoute: typeof DashboardsAdminRoute
  DashboardsComercialRoute: typeof DashboardsComercialRoute
  DashboardsFinanceiroRoute: typeof DashboardsFinanceiroRoute
  DashboardsMarketingRoute: typeof DashboardsMarketingRoute
  DashboardsOperacionalRoute: typeof DashboardsOperacionalRoute
  DashboardsWhatsappRoute: typeof DashboardsWhatsappRoute
  MarketingBancoMidiaRoute: typeof MarketingBancoMidiaRoute
  MarketingCalendarioRoute: typeof MarketingCalendarioRoute
  MarketingConteudosRoute: typeof MarketingConteudosRoute
  PainelAssociadosRoute: typeof PainelAssociadosRoute
  PainelDemandasRoute: typeof PainelDemandasRoute
  PainelRelatoriosRoute: typeof PainelRelatoriosRoute
  PainelResultadosRoute: typeof PainelResultadosRoute
  PeticionamentoIdRoute: typeof PeticionamentoIdRoute
  PeticionamentoBancoPecasRoute: typeof PeticionamentoBancoPecasRoute
  PortalBoletosRoute: typeof PortalBoletosRoute
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalMensagensRoute: typeof PortalMensagensRoute
  PortalPerfilRoute: typeof PortalPerfilRoute
  WhatsappAgenteRoute: typeof WhatsappAgenteRoute
  CasosIndexRoute: typeof CasosIndexRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ComercialIndexRoute: typeof ComercialIndexRoute
  ControladoriaIndexRoute: typeof ControladoriaIndexRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PeticionamentoIndexRoute: typeof PeticionamentoIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  WhatsappIndexRoute: typeof WhatsappIndexRoute
  ApiWebhooksZapsignRoute: typeof ApiWebhooksZapsignRoute
  PortalCasosIdRoute: typeof PortalCasosIdRoute
  WhatsappConversasIdRoute: typeof WhatsappConversasIdRoute
  ApiClientsIdDocumentsDocIdRoute: typeof ApiClientsIdDocumentsDocIdRouteWithChildren
  ApiClientsIdDocumentsIndexRoute: typeof ApiClientsIdDocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/': {
      id: '/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof WhatsappIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peticionamento/': {
      id: '/peticionamento/'
      path: '/peticionamento'
      fullPath: '/peticionamento/'
      preLoaderRoute: typeof PeticionamentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/': {
      id: '/controladoria/'
      path: '/controladoria'
      fullPath: '/controladoria/'
      preLoaderRoute: typeof ControladoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/': {
      id: '/comercial/'
      path: '/comercial'
      fullPath: '/comercial/'
      preLoaderRoute: typeof ComercialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/': {
      id: '/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof CasosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/agente': {
      id: '/whatsapp/agente'
      path: '/whatsapp/agente'
      fullPath: '/whatsapp/agente'
      preLoaderRoute: typeof WhatsappAgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/perfil': {
      id: '/portal/perfil'
      path: '/portal/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof PortalPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/mensagens': {
      id: '/portal/mensagens'
      path: '/portal/mensagens'
      fullPath: '/portal/mensagens'
      preLoaderRoute: typeof PortalMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/portal/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/boletos': {
      id: '/portal/boletos'
      path: '/portal/boletos'
      fullPath: '/portal/boletos'
      preLoaderRoute: typeof PortalBoletosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peticionamento/banco-pecas': {
      id: '/peticionamento/banco-pecas'
      path: '/peticionamento/banco-pecas'
      fullPath: '/peticionamento/banco-pecas'
      preLoaderRoute: typeof PeticionamentoBancoPecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peticionamento/$id': {
      id: '/peticionamento/$id'
      path: '/peticionamento/$id'
      fullPath: '/peticionamento/$id'
      preLoaderRoute: typeof PeticionamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/resultados': {
      id: '/painel/resultados'
      path: '/painel/resultados'
      fullPath: '/painel/resultados'
      preLoaderRoute: typeof PainelResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/relatorios': {
      id: '/painel/relatorios'
      path: '/painel/relatorios'
      fullPath: '/painel/relatorios'
      preLoaderRoute: typeof PainelRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/demandas': {
      id: '/painel/demandas'
      path: '/painel/demandas'
      fullPath: '/painel/demandas'
      preLoaderRoute: typeof PainelDemandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/associados': {
      id: '/painel/associados'
      path: '/painel/associados'
      fullPath: '/painel/associados'
      preLoaderRoute: typeof PainelAssociadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/conteudos': {
      id: '/marketing/conteudos'
      path: '/marketing/conteudos'
      fullPath: '/marketing/conteudos'
      preLoaderRoute: typeof MarketingConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/calendario': {
      id: '/marketing/calendario'
      path: '/marketing/calendario'
      fullPath: '/marketing/calendario'
      preLoaderRoute: typeof MarketingCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/banco-midia': {
      id: '/marketing/banco-midia'
      path: '/marketing/banco-midia'
      fullPath: '/marketing/banco-midia'
      preLoaderRoute: typeof MarketingBancoMidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/whatsapp': {
      id: '/dashboards/whatsapp'
      path: '/dashboards/whatsapp'
      fullPath: '/dashboards/whatsapp'
      preLoaderRoute: typeof DashboardsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/operacional': {
      id: '/dashboards/operacional'
      path: '/dashboards/operacional'
      fullPath: '/dashboards/operacional'
      preLoaderRoute: typeof DashboardsOperacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/marketing': {
      id: '/dashboards/marketing'
      path: '/dashboards/marketing'
      fullPath: '/dashboards/marketing'
      preLoaderRoute: typeof DashboardsMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/financeiro': {
      id: '/dashboards/financeiro'
      path: '/dashboards/financeiro'
      fullPath: '/dashboards/financeiro'
      preLoaderRoute: typeof DashboardsFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/comercial': {
      id: '/dashboards/comercial'
      path: '/dashboards/comercial'
      fullPath: '/dashboards/comercial'
      preLoaderRoute: typeof DashboardsComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/admin': {
      id: '/dashboards/admin'
      path: '/dashboards/admin'
      fullPath: '/dashboards/admin'
      preLoaderRoute: typeof DashboardsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/teses': {
      id: '/controladoria/teses'
      path: '/controladoria/teses'
      fullPath: '/controladoria/teses'
      preLoaderRoute: typeof ControladoriaTesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/prazos': {
      id: '/controladoria/prazos'
      path: '/controladoria/prazos'
      fullPath: '/controladoria/prazos'
      preLoaderRoute: typeof ControladoriaPrazosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/excecoes': {
      id: '/controladoria/excecoes'
      path: '/controladoria/excecoes'
      fullPath: '/controladoria/excecoes'
      preLoaderRoute: typeof ControladoriaExcecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria/decisoes': {
      id: '/controladoria/decisoes'
      path: '/controladoria/decisoes'
      fullPath: '/controladoria/decisoes'
      preLoaderRoute: typeof ControladoriaDecisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/oportunidades': {
      id: '/comercial/oportunidades'
      path: '/comercial/oportunidades'
      fullPath: '/comercial/oportunidades'
      preLoaderRoute: typeof ComercialOportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/leads': {
      id: '/comercial/leads'
      path: '/comercial/leads'
      fullPath: '/comercial/leads'
      preLoaderRoute: typeof ComercialLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/funil': {
      id: '/comercial/funil'
      path: '/comercial/funil'
      fullPath: '/comercial/funil'
      preLoaderRoute: typeof ComercialFunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/email-marketing': {
      id: '/comercial/email-marketing'
      path: '/comercial/email-marketing'
      fullPath: '/comercial/email-marketing'
      preLoaderRoute: typeof ComercialEmailMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/lista': {
      id: '/casos/lista'
      path: '/casos/lista'
      fullPath: '/casos/lista'
      preLoaderRoute: typeof CasosListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/financeiro': {
      id: '/casos/financeiro'
      path: '/casos/financeiro'
      fullPath: '/casos/financeiro'
      preLoaderRoute: typeof CasosFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/$id': {
      id: '/casos/$id'
      path: '/casos/$id'
      fullPath: '/casos/$id'
      preLoaderRoute: typeof CasosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/financeiro/': {
      id: '/casos/financeiro/'
      path: '/'
      fullPath: '/casos/financeiro/'
      preLoaderRoute: typeof CasosFinanceiroIndexRouteImport
      parentRoute: typeof CasosFinanceiroRoute
    }
    '/whatsapp/conversas/$id': {
      id: '/whatsapp/conversas/$id'
      path: '/whatsapp/conversas/$id'
      fullPath: '/whatsapp/conversas/$id'
      preLoaderRoute: typeof WhatsappConversasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/casos/$id': {
      id: '/portal/casos/$id'
      path: '/portal/casos/$id'
      fullPath: '/portal/casos/$id'
      preLoaderRoute: typeof PortalCasosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/financeiro/inadimplencia': {
      id: '/casos/financeiro/inadimplencia'
      path: '/inadimplencia'
      fullPath: '/casos/financeiro/inadimplencia'
      preLoaderRoute: typeof CasosFinanceiroInadimplenciaRouteImport
      parentRoute: typeof CasosFinanceiroRoute
    }
    '/casos/$id/termo': {
      id: '/casos/$id/termo'
      path: '/termo'
      fullPath: '/casos/$id/termo'
      preLoaderRoute: typeof CasosIdTermoRouteImport
      parentRoute: typeof CasosIdRoute
    }
    '/api/webhooks/zapsign': {
      id: '/api/webhooks/zapsign'
      path: '/api/webhooks/zapsign'
      fullPath: '/api/webhooks/zapsign'
      preLoaderRoute: typeof ApiWebhooksZapsignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/$id/termo/elaborar': {
      id: '/casos/$id/termo/elaborar'
      path: '/elaborar'
      fullPath: '/casos/$id/termo/elaborar'
      preLoaderRoute: typeof CasosIdTermoElaborarRouteImport
      parentRoute: typeof CasosIdTermoRoute
    }
    '/api/clients/$id/documents/': {
      id: '/api/clients/$id/documents/'
      path: '/api/clients/$id/documents'
      fullPath: '/api/clients/$id/documents/'
      preLoaderRoute: typeof ApiClientsIdDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id/documents/$docId': {
      id: '/api/clients/$id/documents/$docId'
      path: '/api/clients/$id/documents/$docId'
      fullPath: '/api/clients/$id/documents/$docId'
      preLoaderRoute: typeof ApiClientsIdDocumentsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id/documents/$docId/download': {
      id: '/api/clients/$id/documents/$docId/download'
      path: '/download'
      fullPath: '/api/clients/$id/documents/$docId/download'
      preLoaderRoute: typeof ApiClientsIdDocumentsDocIdDownloadRouteImport
      parentRoute: typeof ApiClientsIdDocumentsDocIdRoute
    }
  }
}

interface CasosIdTermoRouteChildren {
  CasosIdTermoElaborarRoute: typeof CasosIdTermoElaborarRoute
}

const CasosIdTermoRouteChildren: CasosIdTermoRouteChildren = {
  CasosIdTermoElaborarRoute: CasosIdTermoElaborarRoute,
}

const CasosIdTermoRouteWithChildren = CasosIdTermoRoute._addFileChildren(
  CasosIdTermoRouteChildren,
)

interface CasosIdRouteChildren {
  CasosIdTermoRoute: typeof CasosIdTermoRouteWithChildren
}

const CasosIdRouteChildren: CasosIdRouteChildren = {
  CasosIdTermoRoute: CasosIdTermoRouteWithChildren,
}

const CasosIdRouteWithChildren =
  CasosIdRoute._addFileChildren(CasosIdRouteChildren)

interface CasosFinanceiroRouteChildren {
  CasosFinanceiroInadimplenciaRoute: typeof CasosFinanceiroInadimplenciaRoute
  CasosFinanceiroIndexRoute: typeof CasosFinanceiroIndexRoute
}

const CasosFinanceiroRouteChildren: CasosFinanceiroRouteChildren = {
  CasosFinanceiroInadimplenciaRoute: CasosFinanceiroInadimplenciaRoute,
  CasosFinanceiroIndexRoute: CasosFinanceiroIndexRoute,
}

const CasosFinanceiroRouteWithChildren = CasosFinanceiroRoute._addFileChildren(
  CasosFinanceiroRouteChildren,
)

interface ApiClientsIdDocumentsDocIdRouteChildren {
  ApiClientsIdDocumentsDocIdDownloadRoute: typeof ApiClientsIdDocumentsDocIdDownloadRoute
}

const ApiClientsIdDocumentsDocIdRouteChildren: ApiClientsIdDocumentsDocIdRouteChildren =
  {
    ApiClientsIdDocumentsDocIdDownloadRoute:
      ApiClientsIdDocumentsDocIdDownloadRoute,
  }

const ApiClientsIdDocumentsDocIdRouteWithChildren =
  ApiClientsIdDocumentsDocIdRoute._addFileChildren(
    ApiClientsIdDocumentsDocIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DesignSystemRoute: DesignSystemRoute,
  EntrarRoute: EntrarRoute,
  HojeRoute: HojeRoute,
  LoginRoute: LoginRoute,
  TarefasRoute: TarefasRoute,
  CasosIdRoute: CasosIdRouteWithChildren,
  CasosFinanceiroRoute: CasosFinanceiroRouteWithChildren,
  CasosListaRoute: CasosListaRoute,
  ClientesIdRoute: ClientesIdRoute,
  ComercialEmailMarketingRoute: ComercialEmailMarketingRoute,
  ComercialFunilRoute: ComercialFunilRoute,
  ComercialLeadsRoute: ComercialLeadsRoute,
  ComercialOportunidadesRoute: ComercialOportunidadesRoute,
  ControladoriaDecisoesRoute: ControladoriaDecisoesRoute,
  ControladoriaExcecoesRoute: ControladoriaExcecoesRoute,
  ControladoriaPrazosRoute: ControladoriaPrazosRoute,
  ControladoriaTesesRoute: ControladoriaTesesRoute,
  DashboardsAdminRoute: DashboardsAdminRoute,
  DashboardsComercialRoute: DashboardsComercialRoute,
  DashboardsFinanceiroRoute: DashboardsFinanceiroRoute,
  DashboardsMarketingRoute: DashboardsMarketingRoute,
  DashboardsOperacionalRoute: DashboardsOperacionalRoute,
  DashboardsWhatsappRoute: DashboardsWhatsappRoute,
  MarketingBancoMidiaRoute: MarketingBancoMidiaRoute,
  MarketingCalendarioRoute: MarketingCalendarioRoute,
  MarketingConteudosRoute: MarketingConteudosRoute,
  PainelAssociadosRoute: PainelAssociadosRoute,
  PainelDemandasRoute: PainelDemandasRoute,
  PainelRelatoriosRoute: PainelRelatoriosRoute,
  PainelResultadosRoute: PainelResultadosRoute,
  PeticionamentoIdRoute: PeticionamentoIdRoute,
  PeticionamentoBancoPecasRoute: PeticionamentoBancoPecasRoute,
  PortalBoletosRoute: PortalBoletosRoute,
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalMensagensRoute: PortalMensagensRoute,
  PortalPerfilRoute: PortalPerfilRoute,
  WhatsappAgenteRoute: WhatsappAgenteRoute,
  CasosIndexRoute: CasosIndexRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ComercialIndexRoute: ComercialIndexRoute,
  ControladoriaIndexRoute: ControladoriaIndexRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
  PeticionamentoIndexRoute: PeticionamentoIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  WhatsappIndexRoute: WhatsappIndexRoute,
  ApiWebhooksZapsignRoute: ApiWebhooksZapsignRoute,
  PortalCasosIdRoute: PortalCasosIdRoute,
  WhatsappConversasIdRoute: WhatsappConversasIdRoute,
  ApiClientsIdDocumentsDocIdRoute: ApiClientsIdDocumentsDocIdRouteWithChildren,
  ApiClientsIdDocumentsIndexRoute: ApiClientsIdDocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
