// Fonte única (curada e ampliada) das instituições de graduação em Medicina e
// dos hospitais/instituições de residência médica do Brasil.
//
// Decisão do owner (2026-07-18 · story R5-05): "Lista curada editável (ampliada)".
// No MVP estas listas alimentam apenas os <datalist> do cadastro de cliente como
// SUGESTÃO — a digitação livre continua permitida (o valor pode ficar fora da
// lista) e persiste em `system_clients.professional_data` (JSONB).
//
// Evolução futura APROVADA pelo owner (não implementada agora): mover estas
// listas para uma tabela `system_*` editável pelo admin via UI, mantendo esta
// constante como seed/fallback.
//
// Regras: ordenadas alfabeticamente (locale pt-BR) e sem duplicatas.

// Principais faculdades/universidades de Medicina do Brasil (públicas e privadas).
export const INSTITUICOES_GRADUACAO: readonly string[] = [
  "EBMSP — Escola Bahiana de Medicina e Saúde Pública",
  "EMESCAM — Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória",
  "FAMEMA — Faculdade de Medicina de Marília",
  "FAMERP — Faculdade de Medicina de São José do Rio Preto",
  "FCMSCSP — Faculdade de Ciências Médicas da Santa Casa de São Paulo",
  "FEHOSP / FEBASF — Faculdade de Medicina de Barbacena",
  "FMABC — Faculdade de Medicina do ABC (Centro Universitário Saúde ABC)",
  "FpP — Fundação para o Progresso da Medicina",
  "FTC — Faculdade de Tecnologia e Ciências",
  "IMEPAC — Instituto Master de Ensino Presidente Antônio Carlos",
  "ITPAC — Instituto Tocantinense Presidente Antônio Carlos",
  "PUC-Campinas — Pontifícia Universidade Católica de Campinas",
  "PUC-GO — Pontifícia Universidade Católica de Goiás",
  "PUC-MG — Pontifícia Universidade Católica de Minas Gerais",
  "PUC-PR — Pontifícia Universidade Católica do Paraná",
  "PUC-RS — Pontifícia Universidade Católica do Rio Grande do Sul",
  "PUC-SP — Pontifícia Universidade Católica de São Paulo",
  "UCB — Universidade Católica de Brasília",
  "UCPel — Universidade Católica de Pelotas",
  "UCS — Universidade de Caxias do Sul",
  "UEA — Universidade do Estado do Amazonas",
  "UECE — Universidade Estadual do Ceará",
  "UEFS — Universidade Estadual de Feira de Santana",
  "UEL — Universidade Estadual de Londrina",
  "UEM — Universidade Estadual de Maringá",
  "UEMA — Universidade Estadual do Maranhão",
  "UEPA — Universidade do Estado do Pará",
  "UEPG — Universidade Estadual de Ponta Grossa",
  "UERJ — Universidade do Estado do Rio de Janeiro",
  "UERN — Universidade do Estado do Rio Grande do Norte",
  "UESB — Universidade Estadual do Sudoeste da Bahia",
  "UESC — Universidade Estadual de Santa Cruz",
  "UFAC — Universidade Federal do Acre",
  "UFAL — Universidade Federal de Alagoas",
  "UFAM — Universidade Federal do Amazonas",
  "UFBA — Universidade Federal da Bahia",
  "UFC — Universidade Federal do Ceará",
  "UFCSPA — Universidade Federal de Ciências da Saúde de Porto Alegre",
  "UFES — Universidade Federal do Espírito Santo",
  "UFF — Universidade Federal Fluminense",
  "UFG — Universidade Federal de Goiás",
  "UFGD — Universidade Federal da Grande Dourados",
  "UFJF — Universidade Federal de Juiz de Fora",
  "UFMA — Universidade Federal do Maranhão",
  "UFMG — Universidade Federal de Minas Gerais",
  "UFMS — Universidade Federal de Mato Grosso do Sul",
  "UFMT — Universidade Federal de Mato Grosso",
  "UFOP — Universidade Federal de Ouro Preto",
  "UFPA — Universidade Federal do Pará",
  "UFPB — Universidade Federal da Paraíba",
  "UFPE — Universidade Federal de Pernambuco",
  "UFPel — Universidade Federal de Pelotas",
  "UFPI — Universidade Federal do Piauí",
  "UFPR — Universidade Federal do Paraná",
  "UFRB — Universidade Federal do Recôncavo da Bahia",
  "UFRGS — Universidade Federal do Rio Grande do Sul",
  "UFRJ — Universidade Federal do Rio de Janeiro",
  "UFRN — Universidade Federal do Rio Grande do Norte",
  "UFRR — Universidade Federal de Roraima",
  "UFS — Universidade Federal de Sergipe",
  "UFSC — Universidade Federal de Santa Catarina",
  "UFSCar — Universidade Federal de São Carlos",
  "UFSM — Universidade Federal de Santa Maria",
  "UFT — Universidade Federal do Tocantins",
  "UFU — Universidade Federal de Uberlândia",
  "UFV — Universidade Federal de Viçosa",
  "UFVJM — Universidade Federal dos Vales do Jequitinhonha e Mucuri",
  "ULBRA — Universidade Luterana do Brasil",
  "UnB — Universidade de Brasília",
  "UNCISAL — Universidade Estadual de Ciências da Saúde de Alagoas",
  "UNESC — Universidade do Extremo Sul Catarinense",
  "UNESP — Universidade Estadual Paulista",
  "UNICAMP — Universidade Estadual de Campinas",
  "UNIFAL — Universidade Federal de Alfenas",
  "UNIFEI — Universidade Federal de Itajubá",
  "UNIFESP — Universidade Federal de São Paulo",
  "UNIFOR — Universidade de Fortaleza",
  "UNIMONTES — Universidade Estadual de Montes Claros",
  "UNIPAR — Universidade Paranaense",
  "UNISINOS — Universidade do Vale do Rio dos Sinos",
  "UNISUL — Universidade do Sul de Santa Catarina",
  "UNIT — Universidade Tiradentes",
  "UNITAU — Universidade de Taubaté",
  "UNIUBE — Universidade de Uberaba",
  "UNIVALI — Universidade do Vale do Itajaí",
  "UNIVASF — Universidade Federal do Vale do São Francisco",
  "UNOCHAPECÓ — Universidade Comunitária da Região de Chapecó",
  "UNOESTE — Universidade do Oeste Paulista",
  "UPE — Universidade de Pernambuco",
  "USC — Universidade do Sagrado Coração (Bauru)",
  "USP — Universidade de São Paulo",
  "USP-RP — Faculdade de Medicina de Ribeirão Preto (USP)",
];

// Principais hospitais/instituições de residência médica do Brasil.
export const HOSPITAIS_RESIDENCIA: readonly string[] = [
  "AC Camargo Cancer Center (São Paulo)",
  "Beneficência Portuguesa de São Paulo",
  "Complexo Hospitalar Santa Casa de Porto Alegre",
  "Fundação Hospitalar do Estado de Minas Gerais (FHEMIG)",
  "Grupo Hospitalar Conceição (GHC — Porto Alegre)",
  "Hospital Albert Einstein (São Paulo)",
  "Hospital Alemão Oswaldo Cruz (São Paulo)",
  "Hospital Antônio Pedro (HUAP — UFF)",
  "Hospital Barão de Lucena (Recife)",
  "Hospital Base de Brasília",
  "Hospital das Clínicas da FMRP-USP (Ribeirão Preto)",
  "Hospital das Clínicas da FMUSP (HC-FMUSP — São Paulo)",
  "Hospital das Clínicas da UFG (Goiânia)",
  "Hospital das Clínicas da UFMG (Belo Horizonte)",
  "Hospital das Clínicas da UFPE (Recife)",
  "Hospital das Clínicas da UFPR (Curitiba)",
  "Hospital das Clínicas da UNESP (Botucatu)",
  "Hospital de Base de São José do Rio Preto",
  "Hospital de Base do Distrito Federal",
  "Hospital de Clínicas da UFPR (Curitiba)",
  "Hospital de Clínicas da UNICAMP (Campinas)",
  "Hospital de Clínicas de Porto Alegre (HCPA)",
  "Hospital do Câncer de Barretos (Hospital de Amor)",
  "Hospital do Coração (HCor — São Paulo)",
  "Hospital do Servidor Público Estadual de São Paulo (IAMSPE)",
  "Hospital Escola da UFPel",
  "Hospital Geral de Fortaleza (HGF)",
  "Hospital Getúlio Vargas (Recife)",
  "Hospital Israelita Albert Einstein (São Paulo)",
  "Hospital Márcio Cunha (Ipatinga)",
  "Hospital Moinhos de Vento (Porto Alegre)",
  "Hospital Municipal Souza Aguiar (Rio de Janeiro)",
  "Hospital Nossa Senhora da Conceição (Porto Alegre)",
  "Hospital Regional da Asa Norte (HRAN — Brasília)",
  "Hospital Restauração (Recife)",
  "Hospital Santa Casa de Belo Horizonte",
  "Hospital Santa Casa de Misericórdia de São Paulo",
  "Hospital São Lucas da PUCRS (Porto Alegre)",
  "Hospital São Paulo (UNIFESP)",
  "Hospital São Rafael (Salvador)",
  "Hospital Sírio-Libanês (São Paulo)",
  "Hospital Universitário Antônio Pedro (UFF)",
  "Hospital Universitário Cassiano Antônio Moraes (HUCAM — UFES)",
  "Hospital Universitário Clementino Fraga Filho (HUCFF — UFRJ)",
  "Hospital Universitário de Brasília (HUB — UnB)",
  "Hospital Universitário Getúlio Vargas (UFAM)",
  "Hospital Universitário Lauro Wanderley (UFPB)",
  "Hospital Universitário Onofre Lopes (HUOL — UFRN)",
  "Hospital Universitário Oswaldo Cruz (UPE)",
  "Hospital Universitário Pedro Ernesto (HUPE — UERJ)",
  "Hospital Universitário Professor Alberto Antunes (HUPAA — UFAL)",
  "Hospital Universitário Professor Edgard Santos (HUPES — UFBA)",
  "Hospital Universitário Walter Cantídio (HUWC — UFC)",
  "Instituto de Cardiologia do Rio Grande do Sul",
  "Instituto de Medicina Integral Prof. Fernando Figueira (IMIP — Recife)",
  "Instituto do Câncer do Estado de São Paulo (ICESP)",
  "Instituto Dr. José Frota (IJF — Fortaleza)",
  "Instituto Nacional de Câncer (INCA — Rio de Janeiro)",
  "Irmandade da Santa Casa de Misericórdia de Curitiba",
  "Maternidade Escola Assis Chateaubriand (MEAC — UFC)",
  "Santa Casa de Misericórdia de Belo Horizonte",
  "Santa Casa de Misericórdia de Porto Alegre",
  "Santa Casa de Misericórdia de Ribeirão Preto",
  "Santa Casa de Misericórdia de São Paulo",
];
